window.PRODUCTS = [
  {
    "id": "TDI-001",
    "name": "Wysa",
    "vendor": "Touchkin eServices (Wysa Inc.)",
    "platform": "Mobile + Web",
    "url": "https://www.wysa.com/",
    "country": "India / United Kingdom / United States",
    "last_update": "Unknown",
    "stated_pop": "General population (adults; child version available); employees via employer programs",
    "age_range": "13+ (child version separately)",
    "ayaccs": "No",
    "adjacent_aya": "No",
    "general_adult": "Yes",
    "mobile": "Yes",
    "web": "Yes",
    "self_guided": "Yes",
    "therapist_guided": "Yes",
    "hybrid": "Yes",
    "ai_mediated": "Yes",
    "ucd": "Yes",
    "sdt": "Yes",
    "psd": "Yes",
    "equity": "Unknown",
    "wcag": "Unknown",
    "cbt_comorbid": "Yes",
    "symptom_cluster": "No",
    "surv_fit": "No",
    "f_transdx": "Yes",
    "f_coping": "Unknown",
    "f_transition": "No",
    "f_disclosure": "No",
    "f_pain_mind": "Yes",
    "f_gamif": "Yes",
    "f_clusters": "No",
    "f_cbt_cancer": "No",
    "f_jitai": "Unknown",
    "f_peer": "No",
    "f_ccs_custom": "No",
    "f_late_glossary": "No",
    "s_anx": "Yes",
    "s_dep": "Yes",
    "s_pain": "Yes",
    "s_fatigue": "No",
    "s_sleep": "Yes",
    "s_cog": "No",
    "s_isolation": "Unknown",
    "s_rumin": "Unknown",
    "s_health_anx": "Unknown",
    "s_other": "Yes",
    "note": "Transdiagnostic AI-CBT chatbot; covers anxiety, depression, sleep, chronic pain, exam stress, low energy, loneliness, trauma, LGBTQ+. NHS-accelerator listed.",
    "elevator_pitch": "AI-driven mental-wellbeing chat companion that walks users through CBT-based exercises (and optional human therapist add-on) for anxiety, low mood, sleep, chronic pain, and stress.",
    "app_store_url": "https://apps.apple.com/us/app/wysa-mental-wellbeing-ai/id1166585565",
    "google_play_url": "https://play.google.com/store/apps/details?id=bot.touchkin",
    "usage_adoption": "5M+ self-reported users globally; >45 published studies cite improvement on PHQ-9 and GAD-7; NHS-listed (NHS Innovation Accelerator); deployed in employer wellbeing programs and an NHS-Talking-Therapies pilot.",
    "cbt_location": "CBT shows up inside the chat as discrete tool-cards triggered by conversation: 'reframe a thought', 'cognitive restructuring', 'gratitude reflection', 'thought reframer', 'sleep meditation', 'plan a worry-free day', etc. Premium tier adds a chat-based CBT-trained human coach.",
    "cbt_structure": "Open-ended chat with branching tool packs rather than linear sessions; specialised tracks exist (e.g., chronic-pain CBT-based pack used in JMIR study). Self-paced 5–15-min daily check-ins.",
    "cbt_ui_examples": "Penguin avatar, conversational chat bubbles with quick-reply chips. Thought-record screens prompt the user to type the thought, identify the cognitive distortion from a list, then write a balanced alternative.",
    "all_features": "AI chatbot [CBT]; thought reframer [CBT]; cognitive-restructuring exercises [CBT]; behavioural activation prompts [CBT]; problem-solving worksheets [CBT]; mood tracker; sleep stories; meditations; breathing exercises; gratitude journal; physical-activity prompts; in-app SOS routing; optional human coach (premium) [CBT].",
    "cbt_concepts": "Cognitive distortions, thought records, cognitive restructuring/reframing, behavioural activation, problem-solving, relaxation/arousal reduction, psychoeducation, self-monitoring.",
    "cbt_tools": "Conversational chatbot (primary delivery), thought-record screens, mood logs, gratitude journal, breathing exercises, guided meditations, optional human-coach chat.",
    "daily_content": "Daily AI check-ins with mood + reason; suggested 'tools of the day' rotated based on conversation.",
    "psychoeducation": "Brief in-chat explainers on CBT concepts (e.g., what cognitive distortions are, why behavioural activation works), short audio/video clips, FAQs in help centre.",
    "standardized_measures": "PHQ-9 (depression) and GAD-7 (anxiety) administered in-app at intake and follow-up; PROMIS scales reported in some studies.",
    "other_assessments": "Brief in-chat self-rating prompts (mood 1–10, sleep quality, pain intensity) feed into tool recommendations.",
    "cbt_degree": "Core — CBT is the primary therapeutic frame. Mindfulness and positive-psychology content are layered alongside but the active ingredient (per RCT evidence) is the CBT toolset."
  },
  {
    "id": "TDI-002",
    "name": "SilverCloud",
    "vendor": "SilverCloud Health (Amwell)",
    "platform": "Web + Mobile",
    "url": "https://www.silvercloudhealth.com/",
    "country": "Ireland / United States",
    "last_update": "Unknown",
    "stated_pop": "Adults; perinatal; cancer survivors (research RCTs); university students",
    "age_range": "16+",
    "ayaccs": "No",
    "adjacent_aya": "No",
    "general_adult": "Yes",
    "mobile": "Yes",
    "web": "Yes",
    "self_guided": "Yes",
    "therapist_guided": "Yes",
    "hybrid": "Yes",
    "ai_mediated": "No",
    "ucd": "Yes",
    "sdt": "Yes",
    "psd": "Yes",
    "equity": "Unknown",
    "wcag": "Unknown",
    "cbt_comorbid": "Yes",
    "symptom_cluster": "No",
    "surv_fit": "No",
    "f_transdx": "Yes",
    "f_coping": "Yes",
    "f_transition": "No",
    "f_disclosure": "No",
    "f_pain_mind": "Unknown",
    "f_gamif": "No",
    "f_clusters": "No",
    "f_cbt_cancer": "Unknown",
    "f_jitai": "No",
    "f_peer": "No",
    "f_ccs_custom": "No",
    "f_late_glossary": "No",
    "s_anx": "Yes",
    "s_dep": "Yes",
    "s_pain": "Unknown",
    "s_fatigue": "Unknown",
    "s_sleep": "Yes",
    "s_cog": "No",
    "s_isolation": "No",
    "s_rumin": "Yes",
    "s_health_anx": "Yes",
    "s_other": "Yes",
    "note": "Suite of iCBT programs incl. Unified-Protocol transdiagnostic intervention for mixed anxiety/depression; supported and self-guided variants.",
    "elevator_pitch": "Clinically-validated supported-iCBT platform with disorder-specific 'Space from…' programs (Anxiety, Depression, Stress, Sleep, Health Anxiety, Chronic Pain, Mixed) used by NHS, HSE Ireland, and US health systems.",
    "app_store_url": "Unknown (delivered primarily as web app; mobile app exists per individual deployment partners)",
    "google_play_url": "Unknown (deployment-partner-specific)",
    "usage_adoption": "Deployed across NHS Talking Therapies, HSE Ireland, US health systems, universities; cited in dozens of peer-reviewed evaluations; up to 80% of users show improvement; used in cancer-survivor RCTs.",
    "cbt_location": "Modular structured CBT programs branded 'Space from…'. Each program is split into ~10 modules covering psychoeducation → behavioural activation → cognitive restructuring → exposure → relapse prevention.",
    "cbt_structure": "10 modules per program: Getting Started; Understanding Depression & Anxiety; Noticing Feelings; Boosting Behaviour; Spotting Thoughts; Challenging Thoughts; Managing Worry; Core Beliefs (coach-unlocked); Facing Your Fears (coach-unlocked); Bringing It All Together. ~7-week course with weekly coach review.",
    "cbt_ui_examples": "Web/mobile-responsive UI with module-cards, embedded videos, quizzes, drag-and-drop activities, downloadable worksheets, in-line thought-record forms, mood/activity tracker, journal.",
    "all_features": "Modular CBT lessons [CBT]; thought-record / cognitive-restructuring tools [CBT]; behavioural-activation activity scheduler [CBT]; exposure / fear-ladder tool [CBT]; mood tracker; journal; videos; quizzes; coach messaging [CBT support]; downloadable PDF worksheets [CBT]; goal-setting; relaxation/mindfulness audio.",
    "cbt_concepts": "Psychoeducation, behavioural activation, cognitive restructuring, core-belief work, graded exposure, problem-solving, relapse prevention; Unified-Protocol transdiagnostic variant available.",
    "cbt_tools": "Interactive web modules, thought records, activity diaries, fear ladders, journal, downloadable PDFs, coach messaging.",
    "daily_content": "Weekly module assignment (1 module/week); daily homework activities (mood log, activity schedule, thought record).",
    "psychoeducation": "Substantial: each module opens with multimedia psychoeducation (videos, animations, written content) on the CBT model and on the targeted condition.",
    "standardized_measures": "PHQ-9, GAD-7, WHO-5 administered at baseline, mid-program and post; results visualised in a progress dashboard for user and coach.",
    "other_assessments": "WSAS (Work & Social Adjustment Scale) in some deployments; condition-specific measures (e.g., Insomnia Severity Index in Space from Sleep).",
    "cbt_degree": "Core — pure structured iCBT, including the Unified-Protocol transdiagnostic variant developed with Barlow et al."
  },
  {
    "id": "TDI-003",
    "name": "moodgym",
    "vendor": "e-hub Health (Australian National University spin-out)",
    "platform": "Web",
    "url": "https://www.moodgym.com.au/",
    "country": "Australia",
    "last_update": "Unknown",
    "stated_pop": "Adults; emerging-adult/student cohorts",
    "age_range": "16+",
    "ayaccs": "No",
    "adjacent_aya": "No",
    "general_adult": "Yes",
    "mobile": "No",
    "web": "Yes",
    "self_guided": "Yes",
    "therapist_guided": "No",
    "hybrid": "No",
    "ai_mediated": "No",
    "ucd": "Yes",
    "sdt": "Unknown",
    "psd": "Yes",
    "equity": "Yes",
    "wcag": "Unknown",
    "cbt_comorbid": "Yes",
    "symptom_cluster": "No",
    "surv_fit": "No",
    "f_transdx": "Yes",
    "f_coping": "Unknown",
    "f_transition": "No",
    "f_disclosure": "No",
    "f_pain_mind": "No",
    "f_gamif": "No",
    "f_clusters": "No",
    "f_cbt_cancer": "No",
    "f_jitai": "No",
    "f_peer": "No",
    "f_ccs_custom": "No",
    "f_late_glossary": "No",
    "s_anx": "Yes",
    "s_dep": "Yes",
    "s_pain": "No",
    "s_fatigue": "No",
    "s_sleep": "No",
    "s_cog": "No",
    "s_isolation": "No",
    "s_rumin": "Unknown",
    "s_health_anx": "No",
    "s_other": "Yes",
    "note": "Long-running NHMRC-funded iCBT program; clinical-guideline-recommended.",
    "elevator_pitch": "Long-running self-guided web-based interactive CBT training for adults to prevent and reduce depression and anxiety; foundational Australian iCBT program from ANU.",
    "app_store_url": "Unknown (web only)",
    "google_play_url": "Unknown (web only)",
    "usage_adoption": "1.3M+ registered users worldwide; cited in 2016 meta-analysis of 12 trials showing efficacy in adults; recommended in RANZCP clinical-practice guidelines.",
    "cbt_location": "Five sequential modules: Why You Feel the Way You Do; Changing the Way You Think; Changing 'Warpy' Thoughts; Knowing What Makes You Upset; Assertiveness & Interpersonal Skills.",
    "cbt_structure": "5 modules + workbook; ~30–45 min/module; designed to be completed over 4–6 weeks; self-paced with no clinician.",
    "cbt_ui_examples": "Web pages with characters (Elle, Will, etc.) modelling thought-feeling links; embedded interactive quizzes, rating scales, and 'warpy thought' identification exercises.",
    "all_features": "5 CBT modules [CBT]; assessment quizzes [CBT progress]; 'warpy thought' identifier [CBT]; relaxation downloads; workbook; mood-rating scales; interactive characters/scenarios.",
    "cbt_concepts": "Cognitive distortions ('warpy thoughts'), thought-record style reframing, ABC model, behavioural strategies, assertiveness, problem solving.",
    "cbt_tools": "Interactive web exercises, downloadable workbook, quizzes, audio relaxation tracks.",
    "daily_content": "No daily push; module-paced.",
    "psychoeducation": "Substantial — each module begins with character-driven psychoeducation explaining the cognitive model, common distortions, and CBT skills.",
    "standardized_measures": "Goldberg Depression / Anxiety scales used in study evaluations; in-product self-rating quizzes track progress; not a clinical-grade integration.",
    "other_assessments": "Built-in pre/post-module quizzes feed back to user.",
    "cbt_degree": "Core — pure CBT skills training; no mindfulness or other modality."
  },
  {
    "id": "TDI-004",
    "name": "THIS WAY UP",
    "vendor": "St Vincent's Hospital Sydney / UNSW",
    "platform": "Web",
    "url": "https://thiswayup.org.au/",
    "country": "Australia",
    "last_update": "Unknown",
    "stated_pop": "Adults with mixed anxiety + depression; perinatal; chronic pain (separate course)",
    "age_range": "18+",
    "ayaccs": "No",
    "adjacent_aya": "No",
    "general_adult": "Yes",
    "mobile": "No",
    "web": "Yes",
    "self_guided": "Yes",
    "therapist_guided": "Yes",
    "hybrid": "Yes",
    "ai_mediated": "No",
    "ucd": "Yes",
    "sdt": "Unknown",
    "psd": "Yes",
    "equity": "Unknown",
    "wcag": "Unknown",
    "cbt_comorbid": "Yes",
    "symptom_cluster": "No",
    "surv_fit": "No",
    "f_transdx": "Yes",
    "f_coping": "Yes",
    "f_transition": "No",
    "f_disclosure": "No",
    "f_pain_mind": "Yes",
    "f_gamif": "No",
    "f_clusters": "No",
    "f_cbt_cancer": "No",
    "f_jitai": "No",
    "f_peer": "No",
    "f_ccs_custom": "No",
    "f_late_glossary": "No",
    "s_anx": "Yes",
    "s_dep": "Yes",
    "s_pain": "Yes",
    "s_fatigue": "No",
    "s_sleep": "Yes",
    "s_cog": "No",
    "s_isolation": "No",
    "s_rumin": "Unknown",
    "s_health_anx": "Yes",
    "s_other": "Yes",
    "note": "Clinician-prescribable iCBT clinic; transdiagnostic course alongside disorder-specific (OCD, social anxiety, health anxiety, insomnia, chronic pain) courses.",
    "elevator_pitch": "Clinician-prescribable iCBT clinic from St Vincent's / UNSW with 30+ disorder-specific and transdiagnostic CBT courses (anxiety, depression, mixed, OCD, PTSD, health anxiety, chronic pain, insomnia, perinatal).",
    "app_store_url": "Unknown (web platform; courses delivered via browser)",
    "google_play_url": "Unknown (web platform; courses delivered via browser)",
    "usage_adoption": "Used by 10,000s of Australian patients via clinician referral or direct purchase ($59); listed by healthdirect; multiple RCTs and pragmatic trials published.",
    "cbt_location": "Each course is a structured iCBT program with 4–6 'lessons'. Mixed Anxiety & Depression Course is the transdiagnostic flagship; Chronic Pain Course adds CBT-for-pain.",
    "cbt_structure": "Typical course: 6 lessons over 6–12 weeks, lesson-released sequentially every 1–2 weeks. Lesson = comic-style story + skills demo + downloadable lesson summary + homework worksheet.",
    "cbt_ui_examples": "Comic-strip illustration showing a patient applying skills; 'Do Something' homework page with interactive worksheets and reflection prompts; clinician dashboard for prescribers.",
    "all_features": "6-lesson CBT courses [CBT]; lesson summaries (PDF) [CBT]; homework worksheets [CBT]; thought-record templates [CBT]; behavioural-experiment templates [CBT]; symptom tracker; clinician messaging (when prescribed).",
    "cbt_concepts": "Cognitive restructuring, behavioural activation, graded exposure, behavioural experiments, problem solving, relapse prevention; transdiagnostic 'unified' framing in the Mixed course.",
    "cbt_tools": "Online lessons, PDF lesson summaries, structured homework worksheets, symptom-rating tools.",
    "daily_content": "No daily push; weekly lesson + daily homework practice.",
    "psychoeducation": "Strong narrative-driven psychoeducation in every lesson; lesson summaries serve as standalone CBT primers.",
    "standardized_measures": "PHQ-9, GAD-7, K-10 administered at intake and after each lesson; clinician dashboard surfaces scores over time.",
    "other_assessments": "Course-specific symptom measures (e.g., insomnia ISI in Insomnia Course; PCS in Chronic Pain Course).",
    "cbt_degree": "Core — strict structured iCBT; family-level transdiagnostic framework explicitly used in Mixed course."
  },
  {
    "id": "TDI-005",
    "name": "MindSpot Wellbeing",
    "vendor": "MQ Health / Macquarie University",
    "platform": "Web",
    "url": "https://www.mindspot.org.au/",
    "country": "Australia",
    "last_update": "Unknown",
    "stated_pop": "Australians 18+; Mood Mechanic 18-25; Wellbeing Plus 65+; Indigenous Wellbeing Course",
    "age_range": "18+",
    "ayaccs": "No",
    "adjacent_aya": "No",
    "general_adult": "Yes",
    "mobile": "No",
    "web": "Yes",
    "self_guided": "Yes",
    "therapist_guided": "Yes",
    "hybrid": "Yes",
    "ai_mediated": "No",
    "ucd": "Yes",
    "sdt": "Unknown",
    "psd": "Yes",
    "equity": "Yes",
    "wcag": "Unknown",
    "cbt_comorbid": "Yes",
    "symptom_cluster": "No",
    "surv_fit": "No",
    "f_transdx": "Yes",
    "f_coping": "Yes",
    "f_transition": "No",
    "f_disclosure": "No",
    "f_pain_mind": "Unknown",
    "f_gamif": "No",
    "f_clusters": "No",
    "f_cbt_cancer": "No",
    "f_jitai": "No",
    "f_peer": "No",
    "f_ccs_custom": "Unknown",
    "f_late_glossary": "No",
    "s_anx": "Yes",
    "s_dep": "Yes",
    "s_pain": "Unknown",
    "s_fatigue": "No",
    "s_sleep": "Yes",
    "s_cog": "No",
    "s_isolation": "No",
    "s_rumin": "Yes",
    "s_health_anx": "Unknown",
    "s_other": "Yes",
    "note": "National free transdiagnostic iCBT clinic; Mood Mechanic course is the closest age-aligned (18-25) AYA-relevant course.",
    "elevator_pitch": "Australia's free national digital mental-health clinic offering therapist-supported transdiagnostic iCBT courses (Mood Mechanic 18-25; Wellbeing 26-65; Wellbeing Plus 65+; Indigenous Wellbeing).",
    "app_store_url": "Unknown (web platform)",
    "google_play_url": "Unknown (web platform)",
    "usage_adoption": "100,000+ Australians registered since 2012; outcomes published in Psychiatric Services and JMIR; symptoms reduce by ~50% on average.",
    "cbt_location": "Each course = 5 weekly online 'lessons' delivered as illustrated story; transdiagnostic CBT for anxiety + depression with skills covering psychoeducation, cognitive therapy, behavioural activation, graded exposure, sleep, problem solving.",
    "cbt_structure": "5 lessons over 8 weeks; therapist-supported (weekly call/email) or self-paced. Mood Mechanic is the AYA-targeted variant.",
    "cbt_ui_examples": "Illustrated story-style lessons, downloadable lesson summary PDF, homework worksheets, clinician messaging panel.",
    "all_features": "5 transdiagnostic CBT lessons [CBT]; lesson summary PDFs [CBT]; homework worksheets [CBT]; thought-monitoring tool [CBT]; behavioural-activation scheduler [CBT]; graded-exposure tool [CBT]; sleep-management module [CBT]; therapist messaging.",
    "cbt_concepts": "Recognising the symptom cycle, challenging unhelpful thoughts, behavioural activation, graded exposure (overcoming avoidance), sleep training, problem solving, relapse prevention.",
    "cbt_tools": "Lessons, summaries, homework worksheets, thought-record templates, exposure hierarchies, sleep diaries.",
    "daily_content": "No daily push; weekly lesson with daily homework practice.",
    "psychoeducation": "Strong — story-driven psychoeducation about the cognitive-behavioural model embedded in each lesson.",
    "standardized_measures": "PHQ-9, GAD-7, K-10 used at registration, weekly during treatment, post-treatment, and 3-month follow-up.",
    "other_assessments": "PRIME-MD for self-harm screening; suicide-risk follow-up protocol.",
    "cbt_degree": "Core — transdiagnostic CBT explicitly framed at the 'Wellbeing' family level."
  },
  {
    "id": "TDI-006",
    "name": "e-couch",
    "vendor": "e-hub Health (ANU spin-out)",
    "platform": "Web",
    "url": "https://www.ecouch.com.au/",
    "country": "Australia",
    "last_update": "Unknown",
    "stated_pop": "Adults; modules for depression, anxiety, social anxiety, separation/divorce, bereavement",
    "age_range": "18+",
    "ayaccs": "No",
    "adjacent_aya": "No",
    "general_adult": "Yes",
    "mobile": "No",
    "web": "Yes",
    "self_guided": "Yes",
    "therapist_guided": "No",
    "hybrid": "No",
    "ai_mediated": "No",
    "ucd": "Yes",
    "sdt": "Unknown",
    "psd": "Yes",
    "equity": "Unknown",
    "wcag": "Unknown",
    "cbt_comorbid": "Yes",
    "symptom_cluster": "No",
    "surv_fit": "No",
    "f_transdx": "Yes",
    "f_coping": "Unknown",
    "f_transition": "No",
    "f_disclosure": "No",
    "f_pain_mind": "No",
    "f_gamif": "No",
    "f_clusters": "No",
    "f_cbt_cancer": "No",
    "f_jitai": "No",
    "f_peer": "No",
    "f_ccs_custom": "No",
    "f_late_glossary": "No",
    "s_anx": "Yes",
    "s_dep": "Yes",
    "s_pain": "No",
    "s_fatigue": "No",
    "s_sleep": "No",
    "s_cog": "No",
    "s_isolation": "Yes",
    "s_rumin": "Unknown",
    "s_health_anx": "No",
    "s_other": "Yes",
    "note": "CBT + IPT + psychoeducation; bereavement and social-anxiety modules.",
    "elevator_pitch": "ANU/e-hub Health's free self-help website covering depression, anxiety/worry, social anxiety, divorce, and bereavement using CBT, IPT, and psychoeducation.",
    "app_store_url": "Unknown (web only)",
    "google_play_url": "Unknown (web only)",
    "usage_adoption": "Companion to moodgym; used by general public and in research RCTs (Christensen et al.); 3 published RCTs of Depression program; effect sizes comparable to moodgym.",
    "cbt_location": "Each of the 5 programs has an Information module and a Toolkit module; CBT lives inside the Toolkit (e.g., 'Behavioural Activation', 'Activity Scheduling', 'Thinking Tools').",
    "cbt_structure": "Self-paced; users can read the information module then work through any toolkit they choose; no fixed sequence.",
    "cbt_ui_examples": "Text-heavy web pages with downloadable worksheets, structured 'thinking tool' forms, mood diaries, problem-solving templates.",
    "all_features": "5 condition-specific programs [CBT subset]; thinking-tool worksheet [CBT]; activity-scheduling worksheet [CBT]; problem-solving worksheet [CBT]; relaxation audio; mood diary; downloadable PDFs; IPT module [non-CBT].",
    "cbt_concepts": "Behavioural activation, cognitive restructuring, problem solving, relaxation; IPT (interpersonal therapy) added for depression and bereavement.",
    "cbt_tools": "Web modules, downloadable PDF worksheets (thinking tools, activity logs, mood diaries), audio relaxation files.",
    "daily_content": "No daily push.",
    "psychoeducation": "Strong — each program's Information module is essentially a long-form psychoeducation primer.",
    "standardized_measures": "Goldberg / CES-D used in published evaluations; in-product self-rating only.",
    "other_assessments": "Mood diary time series.",
    "cbt_degree": "Mixed — CBT and IPT both used; Depression and Bereavement programs explicitly combine the two."
  },
  {
    "id": "TDI-007",
    "name": "Catch It",
    "vendor": "Universities of Liverpool & Manchester",
    "platform": "Mobile",
    "url": "https://www.liverpool.ac.uk/it/app-directory/catch-it/",
    "country": "United Kingdom",
    "last_update": "Unknown",
    "stated_pop": "General population; mood / anger / anxiety self-management",
    "age_range": "Unknown (consumer app)",
    "ayaccs": "No",
    "adjacent_aya": "No",
    "general_adult": "Yes",
    "mobile": "Yes",
    "web": "No",
    "self_guided": "Yes",
    "therapist_guided": "No",
    "hybrid": "No",
    "ai_mediated": "No",
    "ucd": "Yes",
    "sdt": "Unknown",
    "psd": "Yes",
    "equity": "Unknown",
    "wcag": "Unknown",
    "cbt_comorbid": "Yes",
    "symptom_cluster": "No",
    "surv_fit": "No",
    "f_transdx": "Yes",
    "f_coping": "Unknown",
    "f_transition": "No",
    "f_disclosure": "No",
    "f_pain_mind": "No",
    "f_gamif": "No",
    "f_clusters": "No",
    "f_cbt_cancer": "No",
    "f_jitai": "No",
    "f_peer": "No",
    "f_ccs_custom": "No",
    "f_late_glossary": "Yes",
    "s_anx": "Yes",
    "s_dep": "Yes",
    "s_pain": "No",
    "s_fatigue": "No",
    "s_sleep": "No",
    "s_cog": "No",
    "s_isolation": "No",
    "s_rumin": "Yes",
    "s_health_anx": "No",
    "s_other": "Yes",
    "note": "CBT mood diary (Catch It / Check It / Change It); free Apple/Google.",
    "elevator_pitch": "Free academic-built CBT mood diary from Universities of Liverpool and Manchester; teaches the Catch-It / Check-It / Change-It cycle for re-framing unhelpful thoughts.",
    "app_store_url": "https://apps.apple.com/us/app/catch-it-make-sense-of-moods/id899606280",
    "google_play_url": "https://play.google.com/store/apps/details?id=uk.ac.liv.catchit",
    "usage_adoption": "Free on both stores; published feasibility study showed 84% of user-generated content was CBT-consistent and statistically significant reductions in negative-mood intensity.",
    "cbt_location": "Three-section workflow: Catch It (record mood), Check It (re-frame), Change It (alternative response). Pure CBT thought-record-style structure.",
    "cbt_structure": "Open-ended diary; no sessions or levels; user logs as moods occur.",
    "cbt_ui_examples": "Form-style entry — pick mood, intensity (1–5), context, automatic thought, then prompts for alternative thought and helpful response.",
    "all_features": "Mood diary [CBT]; thought-record (3-step CBT cycle) [CBT]; re-framing prompts [CBT]; PIN protection; export.",
    "cbt_concepts": "Thought records, cognitive re-framing, ABC model.",
    "cbt_tools": "Mood log + thought-record entry form.",
    "daily_content": "User-driven (log when a mood occurs); no scheduled push.",
    "psychoeducation": "Minimal — short in-app description of the CBT model; primarily a tool, not a course.",
    "standardized_measures": "None integrated; not a screener.",
    "other_assessments": "User-rated mood-intensity score is the primary signal.",
    "cbt_degree": "Core — single-purpose CBT thought-record tool."
  },
  {
    "id": "TDI-008",
    "name": "Youper",
    "vendor": "Youper Inc.",
    "platform": "Mobile",
    "url": "https://www.youper.ai/",
    "country": "United States",
    "last_update": "Unknown",
    "stated_pop": "Adults with anxiety/depression; AYA studies in young adults",
    "age_range": "18+ (some AYA evaluations)",
    "ayaccs": "No",
    "adjacent_aya": "No",
    "general_adult": "Yes",
    "mobile": "Yes",
    "web": "No",
    "self_guided": "Yes",
    "therapist_guided": "No",
    "hybrid": "No",
    "ai_mediated": "Yes",
    "ucd": "Yes",
    "sdt": "Unknown",
    "psd": "Yes",
    "equity": "Unknown",
    "wcag": "Unknown",
    "cbt_comorbid": "Yes",
    "symptom_cluster": "No",
    "surv_fit": "No",
    "f_transdx": "Yes",
    "f_coping": "Unknown",
    "f_transition": "No",
    "f_disclosure": "No",
    "f_pain_mind": "No",
    "f_gamif": "No",
    "f_clusters": "No",
    "f_cbt_cancer": "No",
    "f_jitai": "Unknown",
    "f_peer": "No",
    "f_ccs_custom": "No",
    "f_late_glossary": "No",
    "s_anx": "Yes",
    "s_dep": "Yes",
    "s_pain": "No",
    "s_fatigue": "No",
    "s_sleep": "No",
    "s_cog": "No",
    "s_isolation": "No",
    "s_rumin": "Unknown",
    "s_health_anx": "No",
    "s_other": "No",
    "note": "Stanford-validated AI CBT chatbot; emotion-regulation focus; PHQ-9 / GAD-7 outcomes.",
    "elevator_pitch": "AI conversational agent trained on CBT (and other empirically-supported therapies) for adults with anxiety and depression; Stanford-validated.",
    "app_store_url": "https://apps.apple.com/us/app/youper/id1060691513",
    "google_play_url": "https://play.google.com/store/apps/details?id=br.com.youper",
    "usage_adoption": "3M+ users; Google Play 3.9★ (49.4K reviews); Stanford-published validation (PHQ-9 d=0.46, GAD-7 d=0.57 at 2 weeks).",
    "cbt_location": "CBT shows up inside the chat as 'guided exercises' (e.g., Cognitive Restructuring; Worry Time; Behavioural Activation) initiated by the bot or chosen by user.",
    "cbt_structure": "Conversational; no fixed lesson sequence; daily check-in pattern with situationally-suggested CBT exercises.",
    "cbt_ui_examples": "Chat UI; private 'Thought Diary' screens with cognitive-distortion picker; mood-tracking emoji slider; SOS breathing exercise screen.",
    "all_features": "AI chat agent [CBT]; thought-diary (CBT thought record) [CBT]; mood tracker; voice-journaling (premium); meditations; SOS breathing; daily check-ins; AI-personalised CBT exercises [CBT]; library of micro-interventions; coaching content (premium).",
    "cbt_concepts": "Cognitive distortions, thought records, cognitive restructuring, behavioural activation, exposure (worry-time / postponement), problem solving.",
    "cbt_tools": "Chatbot, private thought diary, mood tracker, journaling, audio meditations.",
    "daily_content": "Daily AI check-in with mood + reasons; routine prompts to log emotion.",
    "psychoeducation": "In-chat micro-explanations of CBT concepts; brief written content; audio meditations.",
    "standardized_measures": "PHQ-9 and GAD-7 administered in-app at baseline and follow-ups (used in Stanford trial).",
    "other_assessments": "In-chat mood / emotion-intensity ratings.",
    "cbt_degree": "Core — explicitly CBT-first; mindfulness/meditation is supplementary."
  },
  {
    "id": "TDI-009",
    "name": "Togetherall",
    "vendor": "Togetherall Ltd",
    "platform": "Web + Mobile",
    "url": "https://togetherall.com/",
    "country": "United Kingdom",
    "last_update": "Unknown",
    "stated_pop": "Adults & students; member-led peer community + clinician-monitored self-care courses",
    "age_range": "16+",
    "ayaccs": "No",
    "adjacent_aya": "No",
    "general_adult": "Yes",
    "mobile": "Yes",
    "web": "Yes",
    "self_guided": "Yes",
    "therapist_guided": "No",
    "hybrid": "Yes",
    "ai_mediated": "No",
    "ucd": "Unknown",
    "sdt": "Yes",
    "psd": "Yes",
    "equity": "Yes",
    "wcag": "Unknown",
    "cbt_comorbid": "Yes",
    "symptom_cluster": "No",
    "surv_fit": "No",
    "f_transdx": "Yes",
    "f_coping": "Yes",
    "f_transition": "No",
    "f_disclosure": "No",
    "f_pain_mind": "Unknown",
    "f_gamif": "No",
    "f_clusters": "No",
    "f_cbt_cancer": "No",
    "f_jitai": "No",
    "f_peer": "Yes",
    "f_ccs_custom": "No",
    "f_late_glossary": "No",
    "s_anx": "Yes",
    "s_dep": "Yes",
    "s_pain": "No",
    "s_fatigue": "No",
    "s_sleep": "No",
    "s_cog": "No",
    "s_isolation": "Yes",
    "s_rumin": "Unknown",
    "s_health_anx": "No",
    "s_other": "Yes",
    "note": "Anonymous moderated peer community + GAD-7/PHQ-9 self-assessments + self-guided CBT-based wellness courses.",
    "elevator_pitch": "24/7 anonymous online peer-support community for adults and students, with always-on clinician moderators ('Wall Guides'), validated screeners (PHQ-9/GAD-7), and short self-guided CBT-based wellness courses.",
    "app_store_url": "https://apps.apple.com/us/app/togetherall/id1473459728",
    "google_play_url": "https://play.google.com/store/apps/details?id=com.togetherall.production",
    "usage_adoption": "4.6M+ students at 450+ colleges/universities globally; commissioned by NHS, Veterans Affairs, US universities; multiple peer-reviewed engagement studies.",
    "cbt_location": "Self-care library hosts ~10–15 short CBT-informed courses (anxiety, low mood, sleep, anger) alongside non-CBT content; CBT not the primary offering.",
    "cbt_structure": "Self-paced courses (3–6 short modules each); peer community is the primary product.",
    "cbt_ui_examples": "Forum-like 'wall' with anonymous posts; clinician-moderated; course pages with readings + reflection prompts; assessment dashboard.",
    "all_features": "Anonymous peer community (forums, 'bricks'); 24/7 clinician moderation; validated screeners (PHQ-9, GAD-7); self-guided wellness courses (some CBT-informed [CBT]); journaling; one-to-one chat; resource library.",
    "cbt_concepts": "Light coverage: cognitive re-framing, behavioural activation, sleep hygiene appear in some courses.",
    "cbt_tools": "Online courses, journal, peer threads.",
    "daily_content": "Optional — community is always live; no enforced daily curriculum.",
    "psychoeducation": "Modest — courses provide condensed psychoeducation; primary value is peer connection.",
    "standardized_measures": "PHQ-9 and GAD-7 administered at registration and periodically.",
    "other_assessments": "Engagement metrics (posts, likes) used in evaluation studies.",
    "cbt_degree": "Mixed (CBT loosely referenced) — peer-support is the primary modality; CBT-informed courses are auxiliary content rather than a structured program."
  },
  {
    "id": "TDI-010",
    "name": "Deprexis",
    "vendor": "Gaia AG",
    "platform": "Web",
    "url": "https://deprexis.com/",
    "country": "Germany",
    "last_update": "Unknown",
    "stated_pop": "Adults with depression (DiGA-prescribed)",
    "age_range": "18+",
    "ayaccs": "No",
    "adjacent_aya": "No",
    "general_adult": "Yes",
    "mobile": "No",
    "web": "Yes",
    "self_guided": "Yes",
    "therapist_guided": "Yes",
    "hybrid": "Yes",
    "ai_mediated": "No",
    "ucd": "Yes",
    "sdt": "Yes",
    "psd": "Yes",
    "equity": "Unknown",
    "wcag": "Unknown",
    "cbt_comorbid": "Yes",
    "symptom_cluster": "No",
    "surv_fit": "No",
    "f_transdx": "Yes",
    "f_coping": "Unknown",
    "f_transition": "No",
    "f_disclosure": "No",
    "f_pain_mind": "Yes",
    "f_gamif": "No",
    "f_clusters": "No",
    "f_cbt_cancer": "No",
    "f_jitai": "No",
    "f_peer": "No",
    "f_ccs_custom": "No",
    "f_late_glossary": "No",
    "s_anx": "Yes",
    "s_dep": "Yes",
    "s_pain": "No",
    "s_fatigue": "No",
    "s_sleep": "Yes",
    "s_cog": "No",
    "s_isolation": "No",
    "s_rumin": "Yes",
    "s_health_anx": "No",
    "s_other": "Yes",
    "note": "Germany DiGA-reimbursed CBT-multimodal program; integrates ACT/mindfulness/positive psychology with CBT.",
    "elevator_pitch": "Highly tailored 10-module web-based depression program from Gaia AG; integrates CBT with ACT, mindfulness, IPT, and positive psychology; DiGA-prescribed in Germany.",
    "app_store_url": "Unknown (web platform; mobile-responsive)",
    "google_play_url": "Unknown (web platform)",
    "usage_adoption": "DiGA-reimbursed in Germany since 2020; 11+ RCTs published; effect size d≈0.51 vs control; used in psychotherapy adjunct trials (US VA RCT ongoing 2024).",
    "cbt_location": "CBT is the dominant module set: Behavioural Activation, Cognitive Modification (with thought records and distortions), Problem Solving — though the program also includes ACT/mindfulness, IPT, positive psychology, and dream-work.",
    "cbt_structure": "10 modules (intro; behavioural activation; cognitive modification; lifestyle; acceptance & mindfulness; problem solving; childhood experiences; interpersonal skills; positive psychology; emotion-focused/dream-work). Each 10-60 min; min 6 modules to complete.",
    "cbt_ui_examples": "Simulated dialogue ('Broca' tailoring engine) — Q&A flow, examples, branching content; printable PDF worksheets and summaries; audio recordings; symptom-tracking line charts.",
    "all_features": "10 modules [CBT subset]; behavioural-activation log [CBT]; cognitive-distortion identifier [CBT]; thought-record [CBT]; problem-solving worksheet [CBT]; ACT/mindfulness exercises [non-CBT]; printable PDFs [CBT]; audio; symptom tracker.",
    "cbt_concepts": "Behavioural activation, cognitive distortions, cognitive restructuring (bird's-eye-view; scientist's perspective), problem solving.",
    "cbt_tools": "Interactive web dialogue, worksheets/summaries (PDF), audio, symptom-tracking charts.",
    "daily_content": "Self-paced; modules typically 1–2/week.",
    "psychoeducation": "Strong — Q&A psychoeducation woven throughout; explicit explanations of cognitive distortions, BA rationale, etc.",
    "standardized_measures": "PHQ-9 / BDI-II in trials and DiGA evaluation; in-product symptom tracker.",
    "other_assessments": "User responses tailor content (Broca engine).",
    "cbt_degree": "Mixed (CBT primary) — explicitly multi-modal but CBT-anchored; the program author describes it as 'integrative'."
  },
  {
    "id": "TDI-011",
    "name": "Velibra",
    "vendor": "Gaia AG",
    "platform": "Web",
    "url": "https://www.velibra.de/",
    "country": "Germany",
    "last_update": "Unknown",
    "stated_pop": "Adults with GAD, panic disorder ± agoraphobia, social anxiety disorder",
    "age_range": "18+",
    "ayaccs": "No",
    "adjacent_aya": "No",
    "general_adult": "Yes",
    "mobile": "No",
    "web": "Yes",
    "self_guided": "Yes",
    "therapist_guided": "No",
    "hybrid": "No",
    "ai_mediated": "No",
    "ucd": "Yes",
    "sdt": "Unknown",
    "psd": "Yes",
    "equity": "Unknown",
    "wcag": "Unknown",
    "cbt_comorbid": "Yes",
    "symptom_cluster": "No",
    "surv_fit": "No",
    "f_transdx": "Yes",
    "f_coping": "Yes",
    "f_transition": "No",
    "f_disclosure": "No",
    "f_pain_mind": "No",
    "f_gamif": "No",
    "f_clusters": "No",
    "f_cbt_cancer": "No",
    "f_jitai": "No",
    "f_peer": "No",
    "f_ccs_custom": "No",
    "f_late_glossary": "No",
    "s_anx": "Yes",
    "s_dep": "No",
    "s_pain": "No",
    "s_fatigue": "No",
    "s_sleep": "No",
    "s_cog": "No",
    "s_isolation": "No",
    "s_rumin": "Yes",
    "s_health_anx": "No",
    "s_other": "No",
    "note": "Anxiety-family transdiagnostic (covers 3 anxiety disorders); German DiGA-reimbursed.",
    "elevator_pitch": "DiGA-reimbursed German web-based unguided iCBT for adults with GAD, panic disorder, or social anxiety; 6 modules combining CBT skills with cognitive-bias modification (CBM-I) training.",
    "app_store_url": "Unknown (web platform)",
    "google_play_url": "Unknown (web platform)",
    "usage_adoption": "Reimbursed via DiGA in Germany; RCT in primary care across DE/AT/CH showed 28-45% remission across the three anxiety disorders post-treatment.",
    "cbt_location": "Six structured iCBT modules each followed by a CBM-I training session (interpretation-bias retraining).",
    "cbt_structure": "6 modules; 90-day prescription window, 180-day recommended duration; unguided.",
    "cbt_ui_examples": "Web pages with text + image + audio + downloadable PDF summary/worksheet; daily SMS or email prompts; CBM-I training as ambiguous-scenario completion task.",
    "all_features": "6 CBT modules [CBT]; CBM-I training sessions [CBT]; daily SMS/email reminders; PDF summaries/worksheets [CBT]; thought-record style exercises [CBT]; relaxation audio.",
    "cbt_concepts": "Psychoeducation, cognitive restructuring, interoceptive and situational exposure, problem-solving, relaxation; CBM-I (interpretation-bias retraining).",
    "cbt_tools": "Online modules, PDF worksheets, audio relaxation, CBM-I scenario tasks.",
    "daily_content": "Daily fully-automated SMS/email prompts during treatment.",
    "psychoeducation": "Strong — disorder-specific psychoeducation in each module.",
    "standardized_measures": "GAD-7 / PHQ-9 / SPIN / PDSS used in DiGA evaluation and trials.",
    "other_assessments": "In-product self-rating between modules.",
    "cbt_degree": "Core — pure CBT + an evidence-backed bias-modification add-on (still cognitive-mechanism-based)."
  },
  {
    "id": "TDI-012",
    "name": "SuperBetter",
    "vendor": "SuperBetter LLC",
    "platform": "Mobile + Web",
    "url": "https://www.superbetter.com/",
    "country": "United States",
    "last_update": "Unknown",
    "stated_pop": "Adolescents & adults; resilience and mental-health goals",
    "age_range": "13+",
    "ayaccs": "No",
    "adjacent_aya": "No",
    "general_adult": "Yes",
    "mobile": "Yes",
    "web": "Yes",
    "self_guided": "Yes",
    "therapist_guided": "No",
    "hybrid": "No",
    "ai_mediated": "No",
    "ucd": "Yes",
    "sdt": "Yes",
    "psd": "Yes",
    "equity": "Unknown",
    "wcag": "Unknown",
    "cbt_comorbid": "Yes",
    "symptom_cluster": "No",
    "surv_fit": "No",
    "f_transdx": "Yes",
    "f_coping": "Yes",
    "f_transition": "No",
    "f_disclosure": "No",
    "f_pain_mind": "No",
    "f_gamif": "Yes",
    "f_clusters": "No",
    "f_cbt_cancer": "No",
    "f_jitai": "No",
    "f_peer": "Yes",
    "f_ccs_custom": "No",
    "f_late_glossary": "No",
    "s_anx": "Yes",
    "s_dep": "Yes",
    "s_pain": "No",
    "s_fatigue": "No",
    "s_sleep": "No",
    "s_cog": "No",
    "s_isolation": "No",
    "s_rumin": "No",
    "s_health_anx": "No",
    "s_other": "Yes",
    "note": "Game-based CBT + positive psychology. RCT evidence for depression and anxiety reductions.",
    "elevator_pitch": "Game-based mental-health-and-resilience app where users adopt a secret identity, complete quests, defeat 'bad guys', and check in with allies; integrates positive psychology with CBT principles.",
    "app_store_url": "https://apps.apple.com/us/app/superbetter-mental-health/id536634968",
    "google_play_url": "https://play.google.com/store/apps/details?id=com.superbetter.paid",
    "usage_adoption": "1M+ players lifetime; UPenn and Harvard RCTs show significant reductions in depression and anxiety; largest effect size for depression in 2017 meta-analysis of 22 apps.",
    "cbt_location": "CBT principles surface as 'power-ups' (positive activities), 'bad guys' (negative thoughts/behaviours to fight), 'quests' (graduated challenges), and 'allies' (relatedness/social support).",
    "cbt_structure": "Library of 40+ solo challenges (each 7–30 day arcs) + 90+ host challenges; users adopt one challenge at a time; mostly self-paced, gameful.",
    "cbt_ui_examples": "Quest cards on home; 'epic win' progress bar; secret-identity dashboard; allies-list; bad-guys-defeated counter.",
    "all_features": "Quests [CBT-adjacent — graded exposure / behavioural activation]; power-ups [BA]; bad guys [cognitive defusion / behavioural targets]; allies (relatedness); secret identity (self-concept); progress charts; gamified achievements.",
    "cbt_concepts": "Behavioural activation (power-ups), cognitive re-framing (defeat-the-bad-guy), goal setting, graded exposure (quests), problem solving, social support; positive psychology (savouring, gratitude).",
    "cbt_tools": "In-app quest log, mood/energy/strength check-in, gameful achievements, allies network.",
    "daily_content": "Suggested daily quests/power-ups; gameful streak tracking.",
    "psychoeducation": "Light — gameful framing rather than explicit CBT lessons; embedded micro-tips link to underlying science.",
    "standardized_measures": "PHQ-9 / GAD-7 used in trials, optional in product.",
    "other_assessments": "Self-rated mood/energy/strength check-ins.",
    "cbt_degree": "Mixed — CBT and positive psychology are co-equal anchors; the gameful framing is stronger than explicit CBT framing."
  },
  {
    "id": "TDI-013",
    "name": "BlueIce",
    "vendor": "Oxford Health NHS Foundation Trust / University of Bath",
    "platform": "Mobile",
    "url": "https://oxfordhealth.nhs.uk/blueice/",
    "country": "United Kingdom",
    "last_update": "Unknown",
    "stated_pop": "Adolescents 12-17 with self-harm and emotional dysregulation; CAMHS-prescribed",
    "age_range": "12-17",
    "ayaccs": "No",
    "adjacent_aya": "Yes",
    "general_adult": "No",
    "mobile": "Yes",
    "web": "No",
    "self_guided": "Yes",
    "therapist_guided": "Yes",
    "hybrid": "Yes",
    "ai_mediated": "No",
    "ucd": "Yes",
    "sdt": "Yes",
    "psd": "Yes",
    "equity": "Unknown",
    "wcag": "Unknown",
    "cbt_comorbid": "Yes",
    "symptom_cluster": "No",
    "surv_fit": "No",
    "f_transdx": "Yes",
    "f_coping": "Yes",
    "f_transition": "No",
    "f_disclosure": "No",
    "f_pain_mind": "No",
    "f_gamif": "No",
    "f_clusters": "No",
    "f_cbt_cancer": "No",
    "f_jitai": "Yes",
    "f_peer": "No",
    "f_ccs_custom": "No",
    "f_late_glossary": "No",
    "s_anx": "Yes",
    "s_dep": "Yes",
    "s_pain": "No",
    "s_fatigue": "No",
    "s_sleep": "No",
    "s_cog": "No",
    "s_isolation": "No",
    "s_rumin": "Yes",
    "s_health_anx": "No",
    "s_other": "Yes",
    "note": "CBT + DBT toolbox for adolescent self-harm; mood diary, automatic safety-check routing, emergency contact escalation.",
    "elevator_pitch": "Prescribed UK CAMHS app for 12–17-year-olds who self-harm; CBT/DBT toolbox with mood diary, automatic mood-lifter routing, and emergency-contact escalation.",
    "app_store_url": "Unknown (prescribed app; access via clinician code)",
    "google_play_url": "Unknown (prescribed app)",
    "usage_adoption": "2,520+ young people prescribed across multiple UK CAMHS sites (Bath, Oxfordshire, Cambridgeshire, Manchester, others); RCT (BASH study) and Phase-1 trials show ~73% of adolescents reported reduced self-harm at 12 weeks.",
    "cbt_location": "CBT shows up inside the personalised 'mood-lifter' toolbox triggered by low mood; toolbox combines CBT (e.g., thought challenging, behavioural activation) with DBT skills (distress tolerance) and mindfulness.",
    "cbt_structure": "No formal sessions; user-driven and triggered by low mood. App auto-routes to appropriate toolbox section.",
    "cbt_ui_examples": "Mood-rating slider (0–10) with auto-routing logic; personalised tool-cards; safety-net contact list; emergency-services button.",
    "all_features": "Mood diary [CBT/DBT mood log]; personalised mood-lifter toolbox (CBT + DBT + mindfulness + BA) [CBT subset]; thought-challenge tool [CBT]; behavioural-activation activities [CBT]; relaxation audio; emergency-contact routing; safety check.",
    "cbt_concepts": "Cognitive challenging of distressing thoughts, behavioural activation, problem solving, distress-tolerance (DBT), mindfulness.",
    "cbt_tools": "Mood diary, thought-challenge entries, audio relaxation/mindfulness, automatic routing logic.",
    "daily_content": "User-driven; no enforced daily content.",
    "psychoeducation": "Light — embedded short tips inside toolbox cards.",
    "standardized_measures": "RCSQ self-harm / mood ratings; PHQ-9 / GAD-7 / RCADS in evaluation studies.",
    "other_assessments": "0–10 mood slider drives routing; safety-check questions before each potential self-harm moment.",
    "cbt_degree": "Mixed — explicitly CBT + DBT + mindfulness; CBT is a major component but not the sole framework."
  },
  {
    "id": "TDI-014",
    "name": "COMPASS",
    "vendor": "King's College London",
    "platform": "Web",
    "url": "https://www.kcl.ac.uk/research/compass-an-online-treatment-programme",
    "country": "United Kingdom",
    "last_update": "Unknown",
    "stated_pop": "Adults with long-term physical health conditions experiencing distress, anxiety, or depression",
    "age_range": "18+",
    "ayaccs": "No",
    "adjacent_aya": "No",
    "general_adult": "Yes",
    "mobile": "No",
    "web": "Yes",
    "self_guided": "No",
    "therapist_guided": "Yes",
    "hybrid": "Yes",
    "ai_mediated": "No",
    "ucd": "Yes",
    "sdt": "Unknown",
    "psd": "Yes",
    "equity": "Unknown",
    "wcag": "Unknown",
    "cbt_comorbid": "Yes",
    "symptom_cluster": "No",
    "surv_fit": "Yes",
    "f_transdx": "Yes",
    "f_coping": "Yes",
    "f_transition": "No",
    "f_disclosure": "No",
    "f_pain_mind": "Yes",
    "f_gamif": "No",
    "f_clusters": "No",
    "f_cbt_cancer": "Unknown",
    "f_jitai": "No",
    "f_peer": "No",
    "f_ccs_custom": "Unknown",
    "f_late_glossary": "No",
    "s_anx": "Yes",
    "s_dep": "Yes",
    "s_pain": "Yes",
    "s_fatigue": "Yes",
    "s_sleep": "Unknown",
    "s_cog": "No",
    "s_isolation": "No",
    "s_rumin": "Unknown",
    "s_health_anx": "Yes",
    "s_other": "Yes",
    "note": "Therapist-supported digital CBT calibrated to LTC-related distress; tailored to the survivorship-adjacent population (chronic illness).",
    "elevator_pitch": "King's College London therapist-supported digital CBT for adults with long-term physical health conditions (diabetes, MS, etc.) experiencing distress, anxiety, or depression; 11 modules across 4 'compass quadrants'.",
    "app_store_url": "Unknown (web platform; deployed via NHS partners)",
    "google_play_url": "Unknown (web platform)",
    "usage_adoption": "RCT (Hudson et al., 2024) showed 89% clinically significant improvement in distress vs 45% control; real-world implementation in NHS LTC services; deployment with diabetes services ongoing.",
    "cbt_location": "11 modules organised on a 'compass' diagram: Navigating Compass (mandatory) + 10 themed modules (managing uncertainty, managing symptoms, communication, sleep, fatigue, low mood, worry, etc.) tailored to LTC challenges.",
    "cbt_structure": "First module compulsory (interactive self-assessment + personalised formulation); remaining 10 modules selectable in any order over 10–12 weeks; 5 × 30-min therapist phone calls.",
    "cbt_ui_examples": "Compass diagram navigation; module pages with patient-stories, interactive self-assessment, goal-setting, and embedded thought-record / exposure tasks; PHQ-9/GAD-7 graphical timelines.",
    "all_features": "Self-assessment & formulation tool [CBT]; 11 CBT modules [CBT]; thought-record [CBT]; behavioural-experiment templates [CBT]; goal-setting [CBT]; activity scheduling [CBT]; sleep module; fatigue management; LTC-specific psychoeducation [survivorship-adjacent]; therapist messaging.",
    "cbt_concepts": "Cognitive restructuring, behavioural activation, behavioural experiments, problem solving, graded exposure, symptom-management, third-wave acceptance principles for chronic-condition adjustment.",
    "cbt_tools": "Online modules, structured worksheets, mood/symptom trackers, therapist-call notes.",
    "daily_content": "Module pace (~1/week); homework activities daily.",
    "psychoeducation": "Strong — every module pairs LTC-specific psychoeducation with patient stories and evidence-based CBT skills.",
    "standardized_measures": "PHQ-9 (depression), GAD-7 (anxiety), and a distress measure (DT/CDDS variant) graphically tracked.",
    "other_assessments": "Condition-specific measures used in deployment partnerships.",
    "cbt_degree": "Core — explicitly CBT, adapted to LTC context; this is the closest framework match for survivorship work."
  },
  {
    "id": "TDI-015",
    "name": "Untire",
    "vendor": "Tired of Cancer B.V.",
    "platform": "Mobile",
    "url": "https://www.untire.me/",
    "country": "Netherlands",
    "last_update": "Unknown",
    "stated_pop": "Adult cancer patients & survivors with cancer-related fatigue",
    "age_range": "18+",
    "ayaccs": "No",
    "adjacent_aya": "No",
    "general_adult": "No",
    "mobile": "Yes",
    "web": "No",
    "self_guided": "Yes",
    "therapist_guided": "No",
    "hybrid": "No",
    "ai_mediated": "No",
    "ucd": "Yes",
    "sdt": "Unknown",
    "psd": "Yes",
    "equity": "Unknown",
    "wcag": "Unknown",
    "cbt_comorbid": "Yes",
    "symptom_cluster": "Yes",
    "surv_fit": "Yes",
    "f_transdx": "Yes",
    "f_coping": "Yes",
    "f_transition": "No",
    "f_disclosure": "No",
    "f_pain_mind": "Yes",
    "f_gamif": "No",
    "f_clusters": "Yes",
    "f_cbt_cancer": "Yes",
    "f_jitai": "No",
    "f_peer": "No",
    "f_ccs_custom": "Yes",
    "f_late_glossary": "Unknown",
    "s_anx": "Yes",
    "s_dep": "Yes",
    "s_pain": "No",
    "s_fatigue": "Yes",
    "s_sleep": "Yes",
    "s_cog": "No",
    "s_isolation": "No",
    "s_rumin": "Yes",
    "s_health_anx": "No",
    "s_other": "Yes",
    "note": "Cancer-specific transdiagnostic eHealth: CBT (My themes) + MBSR + physical activity + positive psychology.",
    "elevator_pitch": "Cancer-specific eHealth app for adult cancer patients and survivors managing cancer-related fatigue; CBT (My themes) + MBSR + physical-activity coaching + positive-psychology tips, in 25 countries.",
    "app_store_url": "https://apps.apple.com/app/untire/id1394778517",
    "google_play_url": "https://play.google.com/store/apps/details?id=com.tiredofcancerapp.untirenxt.basic",
    "usage_adoption": "Available free in 25 countries; ranked one of ORCHA's top-5 cancer digital solutions globally (2021); RCT (Spahrkäs et al.) showed d=0.40 fatigue, d=0.32 QoL improvements; CE-marked medical device.",
    "cbt_location": "CBT lives in 'My themes' module — psychoeducation + thought records + behavioural-activation around fatigue, worry, sleep, and low mood. Mediation analysis (Spahrkäs 2022) shows fatigue catastrophising and depression are the active mechanisms.",
    "cbt_structure": "Four content pillars: My themes (CBT psychoeducation + reflective exercises); My exercises (mindfulness/MBSR audio); Physical activity (graded movement); Tips (positive psychology). Self-paced; weekly Quick-Scan check-in.",
    "cbt_ui_examples": "Theme cards (e.g., 'The fatigue trap', 'Worry'), reflective journal entries, audio mindfulness players, graded-activity charts, weekly Quick-Scan summary.",
    "all_features": "My themes — psychoeducation + journaling [CBT]; thought-record-style reflections [CBT]; behavioural-activation activity planner [CBT]; mindfulness audio [non-CBT]; physical-activity coaching; Quick-Scan weekly self-rating; positive-psychology tips.",
    "cbt_concepts": "Fatigue catastrophising, cognitive restructuring, behavioural activation (graded activity), problem solving, sleep hygiene; mediation evidence supports cognitive-mechanism activity.",
    "cbt_tools": "Reflective journal, activity planner, mood + energy logs, weekly Quick-Scan.",
    "daily_content": "Tips library; weekly Quick-Scan; user-paced theme work.",
    "psychoeducation": "Strong — cancer-fatigue-specific psychoeducation throughout My themes.",
    "standardized_measures": "Used in RCTs: CIS-fatigue, EORTC QLQ-C30 (fatigue + QoL); in-app Quick-Scan tracks fatigue, burden, happiness, satisfaction, energy leaks weekly.",
    "other_assessments": "Cognitive-mechanism mediators (fatigue catastrophising, depressive symptoms, mindfulness) measured in studies.",
    "cbt_degree": "Mixed — CBT for cancer-related fatigue is a primary component, but mindfulness-based stress-reduction and physical-activity coaching are co-equal pillars."
  },
  {
    "id": "TDI-016",
    "name": "iCanThrive",
    "vendor": "University of Virginia (research deployment)",
    "platform": "Mobile",
    "url": "https://cancer.jmir.org/2020/1/e15750/",
    "country": "United States",
    "last_update": "Unknown",
    "stated_pop": "Women cancer survivors within 5 years post-treatment (research-deployed)",
    "age_range": "18+",
    "ayaccs": "No",
    "adjacent_aya": "No",
    "general_adult": "Yes",
    "mobile": "Yes",
    "web": "No",
    "self_guided": "Yes",
    "therapist_guided": "No",
    "hybrid": "Yes",
    "ai_mediated": "No",
    "ucd": "Yes",
    "sdt": "Unknown",
    "psd": "Yes",
    "equity": "Unknown",
    "wcag": "Unknown",
    "cbt_comorbid": "Yes",
    "symptom_cluster": "No",
    "surv_fit": "Yes",
    "f_transdx": "Yes",
    "f_coping": "Yes",
    "f_transition": "No",
    "f_disclosure": "No",
    "f_pain_mind": "Yes",
    "f_gamif": "No",
    "f_clusters": "No",
    "f_cbt_cancer": "Yes",
    "f_jitai": "No",
    "f_peer": "No",
    "f_ccs_custom": "Yes",
    "f_late_glossary": "Unknown",
    "s_anx": "Yes",
    "s_dep": "Yes",
    "s_pain": "No",
    "s_fatigue": "No",
    "s_sleep": "Yes",
    "s_cog": "No",
    "s_isolation": "No",
    "s_rumin": "Yes",
    "s_health_anx": "Unknown",
    "s_other": "Yes",
    "note": "Cancer-survivorship CBT/ACT mobile app with phone coaching; pilot evidence for depression and sleep.",
    "elevator_pitch": "8-module mobile self-help intervention drawn from CBT and acceptance-based therapies for women cancer survivors within 5 years post-treatment.",
    "app_store_url": "Unknown (research deployment)",
    "google_play_url": "https://play.google.com/store/apps/details?id=com.qualtricsreactnative",
    "usage_adoption": "Pilot study (n=28) showed significant reductions in depression and sleep disruption; available on Google Play (US) following research study; current production status unclear (verify in human review).",
    "cbt_location": "Eight discrete CBT/ACT exercise modules: promoting a grateful outlook; challenging negative thoughts; living a value-driven life; problem solving; savouring positive experiences; reducing worry; breathing relaxation; identifying emotions.",
    "cbt_structure": "8 self-paced exercise modules; supported by once-weekly phone-coaching call from a clinician.",
    "cbt_ui_examples": "Exercise screens with prompt + reflection field; 'Challenge a Thought' module asks user to type negative thought, identify distortion, write alternative; triangle-breathing video.",
    "all_features": "8 CBT/ACT exercise modules [CBT subset]; thought-challenging module [CBT]; problem-solving module [CBT]; behavioural-activation (savouring) module; values-clarification (ACT) module [non-CBT]; breathing-relaxation video; phone coaching.",
    "cbt_concepts": "Cognitive restructuring (thought-challenging), problem solving, behavioural activation (savouring), worry-time, relaxation; ACT values clarification.",
    "cbt_tools": "Exercise modules, journaling fields, video, phone coaching.",
    "daily_content": "Designed for daily 5–15 min use during the 8-week pilot.",
    "psychoeducation": "Moderate — short cancer-survivor-tailored explainers within each module.",
    "standardized_measures": "CES-D (depression), PSQI (sleep), POMS (mood) used in pilot.",
    "other_assessments": "Brief in-app reflection ratings.",
    "cbt_degree": "Mixed — CBT and ACT are co-equal; explicitly described as drawing from 'CBT and acceptance-based therapies'."
  },
  {
    "id": "TDI-017",
    "name": "iCanCope with Pain",
    "vendor": "SickKids / UHN (Stinson, Lalloo et al.)",
    "platform": "Mobile + Web",
    "url": "https://www.sickkids.ca/en/care-services/clinics/icancope-program/",
    "country": "Canada",
    "last_update": "Unknown",
    "stated_pop": "Adolescents with chronic pain (juvenile arthritis, sickle cell, post-op, persistent pain)",
    "age_range": "12-18 (adolescents)",
    "ayaccs": "No",
    "adjacent_aya": "Yes",
    "general_adult": "No",
    "mobile": "Yes",
    "web": "Yes",
    "self_guided": "Yes",
    "therapist_guided": "Unknown",
    "hybrid": "Yes",
    "ai_mediated": "No",
    "ucd": "Yes",
    "sdt": "Yes",
    "psd": "Yes",
    "equity": "Yes",
    "wcag": "Unknown",
    "cbt_comorbid": "Yes",
    "symptom_cluster": "Yes",
    "surv_fit": "Yes",
    "f_transdx": "Yes",
    "f_coping": "Yes",
    "f_transition": "Yes",
    "f_disclosure": "No",
    "f_pain_mind": "Yes",
    "f_gamif": "Yes",
    "f_clusters": "Yes",
    "f_cbt_cancer": "No",
    "f_jitai": "Yes",
    "f_peer": "Yes",
    "f_ccs_custom": "Unknown",
    "f_late_glossary": "Unknown",
    "s_anx": "Yes",
    "s_dep": "Yes",
    "s_pain": "Yes",
    "s_fatigue": "No",
    "s_sleep": "Yes",
    "s_cog": "No",
    "s_isolation": "Yes",
    "s_rumin": "Unknown",
    "s_health_anx": "No",
    "s_other": "Yes",
    "note": "Birnie/Stinson UCD exemplar; symptom trackers across pain/sleep/mood/function/energy; CBT coping toolbox + goal-setting + peer support + age-appropriate education.",
    "elevator_pitch": "Birnie/Stinson SickKids/UHN paediatric chronic-pain self-management app for 12–18-year-olds with chronic pain (juvenile arthritis, sickle cell, post-op pain, persistent pain); CBT coping toolbox + symptom tracking + goal setting + age-appropriate education.",
    "app_store_url": "https://apps.apple.com/us/app/icancope-with-pain/id6451092151",
    "google_play_url": "https://play.google.com/store/apps/details?id=ca.centrefordigitaltherapeutics.icancopewithpain",
    "usage_adoption": "Pilot RCTs across multiple pain conditions; iCanCope POP (post-op) and JIA pilots published; iCanCope-SCD for sickle cell ongoing; access currently limited to research participants in some deployments.",
    "cbt_location": "CBT lives in the 'Coping Toolbox' (Component III) — pain-specific cognitive and behavioural strategies; complemented by symptom trackers, goal-setting, social support, and age-appropriate pain education.",
    "cbt_structure": "Five evidence-based components rather than sequential lessons: trackers; goal-setting; coping toolbox; social support; education.",
    "cbt_ui_examples": "Tap-to-rate trackers (pain, sleep, mood, function, energy on 0–10 scales); goal-setting form; coping toolbox cards (muscle relaxation, guided imagery, mindfulness, abdominal breathing, distraction, thought-challenging).",
    "all_features": "Symptom trackers (pain/sleep/mood/function/energy); goal-setting [CBT]; CBT coping toolbox [CBT]; muscle relaxation [CBT]; guided imagery [CBT]; mindfulness; abdominal breathing [CBT]; thought-challenging cards [CBT]; pain-education library; moderated peer-discussion 'question of the day' boards; reports/graphs.",
    "cbt_concepts": "Pain-specific cognitive restructuring, behavioural activation (graded activity, pacing), relaxation, attention diversion, problem solving, exposure to feared movement.",
    "cbt_tools": "Real-time trackers, goal-setting wizard, coping-tool cards, education library, peer discussion boards.",
    "daily_content": "Daily real-time symptom logging; question-of-the-day in social-support feed.",
    "psychoeducation": "Strong — pain-specific multimedia education (animations, videos, audio) on pain neuroscience and coping.",
    "standardized_measures": "PROMIS pain interference, NRS pain intensity, PSQI, mood scales in trials; built-in trackers visualise time-series.",
    "other_assessments": "Personalised goal achievement; functional-activity log.",
    "cbt_degree": "Core — CBT-for-pain is the active framework; closest UCD exemplar for AYA-adjacent chronic-illness work."
  },
  {
    "id": "TDI-018",
    "name": "MindShift CBT",
    "vendor": "Anxiety Canada",
    "platform": "Mobile",
    "url": "https://mindshiftcbt.com/",
    "country": "Canada",
    "last_update": "Unknown",
    "stated_pop": "Youth and adults with anxiety (GAD, panic, social anxiety, phobias, health anxiety)",
    "age_range": "13+",
    "ayaccs": "No",
    "adjacent_aya": "No",
    "general_adult": "Yes",
    "mobile": "Yes",
    "web": "No",
    "self_guided": "Yes",
    "therapist_guided": "No",
    "hybrid": "No",
    "ai_mediated": "No",
    "ucd": "Yes",
    "sdt": "Yes",
    "psd": "Yes",
    "equity": "Yes",
    "wcag": "Unknown",
    "cbt_comorbid": "Yes",
    "symptom_cluster": "No",
    "surv_fit": "No",
    "f_transdx": "Yes",
    "f_coping": "Yes",
    "f_transition": "No",
    "f_disclosure": "No",
    "f_pain_mind": "No",
    "f_gamif": "No",
    "f_clusters": "No",
    "f_cbt_cancer": "No",
    "f_jitai": "No",
    "f_peer": "Yes",
    "f_ccs_custom": "No",
    "f_late_glossary": "No",
    "s_anx": "Yes",
    "s_dep": "No",
    "s_pain": "No",
    "s_fatigue": "No",
    "s_sleep": "No",
    "s_cog": "No",
    "s_isolation": "No",
    "s_rumin": "Yes",
    "s_health_anx": "Yes",
    "s_other": "No",
    "note": "Single-symptom-domain (anxiety family). Spans GAD/panic/social/phobia/health-anxiety variants.",
    "elevator_pitch": "Free Anxiety-Canada-developed CBT toolkit for youth and adults with anxiety (GAD, panic, social, phobias, health anxiety); thought journal, fear ladder, coping cards, community forum.",
    "app_store_url": "https://apps.apple.com/ca/app/mindshift-cbt-anxiety-relief/id634684825",
    "google_play_url": "https://play.google.com/store/apps/details?id=com.bstro.MindShift",
    "usage_adoption": "770K+ Google Play downloads (Similarweb estimate, 2024); ~35K downloads/month; published feasibility RCT in psychiatric inpatients; widely used by Canadian mental-health services.",
    "cbt_location": "Multiple CBT toolsets accessed from a home menu — Quick Relief, Thought Journal, Coping Cards, Belief Experiment, Facing Fears (fear ladder), Chill Zone, Goals.",
    "cbt_structure": "Tool-first (not lesson-first); user opens whichever tool fits the moment. Anxiety-Canada also offers separate 'Healthy Habits' check-ins and structured 'Chill Out Tools'.",
    "cbt_ui_examples": "Thought-journal form (situation → thoughts → feelings → reframe), fear-ladder builder (write feared situation + rank), coping-cards library, breathing-bubble Chill Zone.",
    "all_features": "Thought Journal [CBT]; Coping Cards [CBT]; Belief Experiment [CBT]; Facing Fears (fear ladder/exposure) [CBT]; Chill Zone (breathing) [CBT]; Quick Relief; Healthy Habits; Goal-Setting [CBT]; Check-Ins; Community Forum [peer support].",
    "cbt_concepts": "Cognitive distortions, thought records, behavioural experiments (Belief Experiment), graded exposure (Fear Ladder), relaxation, goal setting.",
    "cbt_tools": "Thought-journal, fear-ladder builder, coping cards, belief-experiment template, breathing exercises, check-ins.",
    "daily_content": "Daily check-in option; otherwise tool-driven.",
    "psychoeducation": "Strong — anxiety-disorder-specific psychoeducation (GAD, social anxiety, panic, health anxiety, phobias) referenced from Anxiety-Canada library.",
    "standardized_measures": "Self-rated anxiety scale at intake/follow-up (not PHQ-9/GAD-7 by default).",
    "other_assessments": "Mood/anxiety tracker over time.",
    "cbt_degree": "Core — explicit CBT toolset; mindfulness present but secondary."
  },
  {
    "id": "TDI-019",
    "name": "Daylight (DaylightRx)",
    "vendor": "Big Health",
    "platform": "Mobile",
    "url": "https://www.bighealth.com/daylight",
    "country": "United Kingdom / United States",
    "last_update": "Unknown",
    "stated_pop": "Adults with worry / generalised anxiety disorder",
    "age_range": "18+",
    "ayaccs": "No",
    "adjacent_aya": "No",
    "general_adult": "Yes",
    "mobile": "Yes",
    "web": "No",
    "self_guided": "Yes",
    "therapist_guided": "Yes",
    "hybrid": "Yes",
    "ai_mediated": "No",
    "ucd": "Yes",
    "sdt": "Yes",
    "psd": "Yes",
    "equity": "Unknown",
    "wcag": "Unknown",
    "cbt_comorbid": "No",
    "symptom_cluster": "No",
    "surv_fit": "No",
    "f_transdx": "No",
    "f_coping": "Yes",
    "f_transition": "No",
    "f_disclosure": "No",
    "f_pain_mind": "No",
    "f_gamif": "No",
    "f_clusters": "No",
    "f_cbt_cancer": "No",
    "f_jitai": "No",
    "f_peer": "No",
    "f_ccs_custom": "No",
    "f_late_glossary": "No",
    "s_anx": "Yes",
    "s_dep": "No",
    "s_pain": "No",
    "s_fatigue": "No",
    "s_sleep": "No",
    "s_cog": "No",
    "s_isolation": "No",
    "s_rumin": "Yes",
    "s_health_anx": "No",
    "s_other": "No",
    "note": "Single-symptom (worry/GAD). FDA-cleared (DaylightRx).",
    "elevator_pitch": "FDA-cleared (DaylightRx) digital CBT for adults 22+ with worry / generalised anxiety disorder, delivered via voice-led interactive lessons on a phone.",
    "app_store_url": "https://apps.apple.com/us/app/daylight-worry-less/id1555718085",
    "google_play_url": "https://play.google.com/store/apps/details?id=com.bighealth.daylight.platgen.production",
    "usage_adoption": "FDA-cleared (DaylightRx, 2024); deployed by US health systems; RCT (Carl et al.) showed 71% remission of GAD by week 10 (vs 33% control); Big Health is enterprise-deployed.",
    "cbt_location": "CBT delivered as structured lessons on applied relaxation, stimulus control, cognitive restructuring, and exposure to worry — explicitly framed as CBT for GAD.",
    "cbt_structure": "Daily lessons (~10 min each) over weeks; audio-led, voice-actor format; sequential, not branching.",
    "cbt_ui_examples": "Audio-first lesson player with voice-over guide; cards prompting written reflections; symptom-tracker dashboards; reminders.",
    "all_features": "Voice-led CBT lessons [CBT]; applied-relaxation training [CBT]; stimulus-control exercises [CBT]; cognitive-restructuring exercises [CBT]; exposure-to-worry tasks [CBT]; daily practice prompts; progress charts; GAD-7 check-ins.",
    "cbt_concepts": "Applied relaxation, stimulus control (worry-time / postponement), cognitive restructuring, imaginal exposure to worry.",
    "cbt_tools": "Audio lessons, structured worksheets, in-app reflection prompts.",
    "daily_content": "Yes — designed for ~10 min/day across the program window.",
    "psychoeducation": "Strong — every lesson is framed psychoeducationally before delivering the skill.",
    "standardized_measures": "GAD-7 is the primary outcome and built-in tracker; PHQ-9 in some deployments.",
    "other_assessments": "Worry-frequency self-ratings.",
    "cbt_degree": "Core — pure CBT for GAD."
  },
  {
    "id": "TDI-020",
    "name": "Sleepio (SleepioRx)",
    "vendor": "Big Health",
    "platform": "Mobile + Web",
    "url": "https://www.bighealth.com/sleepio",
    "country": "United Kingdom / United States",
    "last_update": "Unknown",
    "stated_pop": "Adults with insomnia disorder; secondary anxiety/depression effects in evidence base",
    "age_range": "18+",
    "ayaccs": "No",
    "adjacent_aya": "No",
    "general_adult": "Yes",
    "mobile": "Yes",
    "web": "Yes",
    "self_guided": "Yes",
    "therapist_guided": "Yes",
    "hybrid": "Yes",
    "ai_mediated": "No",
    "ucd": "Yes",
    "sdt": "Yes",
    "psd": "Yes",
    "equity": "Unknown",
    "wcag": "Unknown",
    "cbt_comorbid": "No",
    "symptom_cluster": "No",
    "surv_fit": "No",
    "f_transdx": "No",
    "f_coping": "Yes",
    "f_transition": "No",
    "f_disclosure": "No",
    "f_pain_mind": "No",
    "f_gamif": "No",
    "f_clusters": "No",
    "f_cbt_cancer": "No",
    "f_jitai": "No",
    "f_peer": "No",
    "f_ccs_custom": "No",
    "f_late_glossary": "No",
    "s_anx": "Yes",
    "s_dep": "Yes",
    "s_pain": "No",
    "s_fatigue": "Yes",
    "s_sleep": "Yes",
    "s_cog": "No",
    "s_isolation": "No",
    "s_rumin": "Yes",
    "s_health_anx": "No",
    "s_other": "Yes",
    "note": "Primarily single-target (insomnia) but RCT evidence for secondary anxiety, depression, fatigue improvement. NICE-recommended.",
    "elevator_pitch": "NICE-recommended, FDA-cleared (SleepioRx) digital CBT-I for adults with insomnia disorder; 6 weekly sessions led by an animated 'Prof' avatar based on Prof Colin Espie's CBT-I protocol.",
    "app_store_url": "https://apps.apple.com/gb/app/sleepio/id1538191784",
    "google_play_url": "Unknown (UK / US enterprise primary; mobile available via partner deployments)",
    "usage_adoption": "NICE-recommended (MTG70); FDA-cleared (SleepioRx); >12 RCTs; 76% achieve clinical improvement on insomnia; large UK NHS deployment.",
    "cbt_location": "Pure CBT-I: sleep-restriction, stimulus-control, cognitive restructuring of sleep-related thoughts, sleep hygiene.",
    "cbt_structure": "6 weekly 20-min sessions with 'The Prof' avatar; each session unlocks 1 week after the previous; daily sleep-diary completion between sessions.",
    "cbt_ui_examples": "'The Prof' animated character delivers each session as a guided dialogue; sleep-diary input form; 'Sleep school' library articles; community discussion board.",
    "all_features": "6 CBT-I sessions [CBT]; daily sleep diary [CBT]; sleep-restriction calculator [CBT]; stimulus-control protocol [CBT]; cognitive-restructuring of sleep beliefs [CBT]; sleep-hygiene library; community board; library of articles.",
    "cbt_concepts": "Sleep restriction, stimulus control, cognitive restructuring of dysfunctional sleep beliefs, paradoxical intention, sleep hygiene, racing-mind techniques.",
    "cbt_tools": "Animated 'Prof' sessions, daily sleep diary, schedule calculator, sleep-thought journal.",
    "daily_content": "Daily sleep-diary entry; weekly session.",
    "psychoeducation": "Strong — embedded sleep-science psychoeducation across each session and the 'Sleep School' library.",
    "standardized_measures": "ISI (Insomnia Severity Index) primary; SCI (Sleep Condition Indicator); PHQ-9 / GAD-7 used in some deployments.",
    "other_assessments": "Sleep-diary-derived metrics (sleep efficiency, total sleep time, latency).",
    "cbt_degree": "Core — gold-standard CBT-I; nothing non-CBT in the active protocol."
  },
  {
    "id": "TDI-021",
    "name": "Lumi Nova",
    "vendor": "BfB Labs",
    "platform": "Mobile",
    "url": "https://luminova.app/",
    "country": "United Kingdom",
    "last_update": "Unknown",
    "stated_pop": "Children 7-12 with mild-to-moderate anxiety (GAD, social, separation, panic, phobias)",
    "age_range": "7-12",
    "ayaccs": "No",
    "adjacent_aya": "Yes",
    "general_adult": "No",
    "mobile": "Yes",
    "web": "No",
    "self_guided": "Yes",
    "therapist_guided": "No",
    "hybrid": "No",
    "ai_mediated": "No",
    "ucd": "Yes",
    "sdt": "Yes",
    "psd": "Yes",
    "equity": "Unknown",
    "wcag": "Unknown",
    "cbt_comorbid": "No",
    "symptom_cluster": "No",
    "surv_fit": "No",
    "f_transdx": "No",
    "f_coping": "Yes",
    "f_transition": "No",
    "f_disclosure": "No",
    "f_pain_mind": "No",
    "f_gamif": "Yes",
    "f_clusters": "No",
    "f_cbt_cancer": "No",
    "f_jitai": "No",
    "f_peer": "No",
    "f_ccs_custom": "No",
    "f_late_glossary": "No",
    "s_anx": "Yes",
    "s_dep": "No",
    "s_pain": "No",
    "s_fatigue": "No",
    "s_sleep": "No",
    "s_cog": "No",
    "s_isolation": "No",
    "s_rumin": "No",
    "s_health_anx": "No",
    "s_other": "No",
    "note": "Single-symptom (anxiety). Class-1 SaMD; NICE-recommended; immersive game-based exposure CBT.",
    "elevator_pitch": "NICE-recommended Class-1 SaMD therapeutic game for children 7-12 with mild-to-moderate anxiety; immersive intergalactic adventure that delivers exposure-based CBT.",
    "app_store_url": "https://apps.apple.com/gb/app/lumi-nova-tales-of-courage/id1476821007",
    "google_play_url": "https://play.google.com/store/apps/details?id=com.bfblabs.game",
    "usage_adoption": "NICE-recommended; commissioned by NHS (Oxleas, Bexley/Greenwich); peer-reviewed evaluation studies (Lockwood et al.) show reductions in anxiety across all subdomains in 8 weeks.",
    "cbt_location": "Exposure-CBT is the active ingredient — child sets a worry-related goal, builds a graded ladder of exposure 'Missions' (challenges), and reflects on each completion in-game.",
    "cbt_structure": "8 game levels; each Mission broken into 3 smaller goals; 14 anxiety-related goals available (social, separation, specific phobias).",
    "cbt_ui_examples": "Space adventure game UI; character creation; planet exploration; mission-card with before/after reflection prompts; treasure/achievement collection.",
    "all_features": "Game-based exposure CBT [CBT]; mission/goal builder (graded ladder) [CBT]; before/after reflection prompts [CBT]; psychoeducation cut-scenes [CBT]; gamification (treasure, planets, levels); auto-conclude (30-40 min limits screen time); parent dashboard.",
    "cbt_concepts": "Graded exposure, behavioural experiments, psychoeducation, self-monitoring.",
    "cbt_tools": "In-game challenges (exposure tasks), reflection journal, parent dashboard, psychoeducation animations.",
    "daily_content": "Designed for ~30-40 min/day during the 6-8-week intervention.",
    "psychoeducation": "Strong — animated psychoeducation cut-scenes about anxiety and avoidance.",
    "standardized_measures": "Goal-Based Outcomes (GBO), self-rated worry/distress; RCADS/SCAS in evaluation.",
    "other_assessments": "In-game progress data.",
    "cbt_degree": "Core — exposure-CBT is the explicit active ingredient."
  },
  {
    "id": "TDI-022",
    "name": "CBT-i Coach",
    "vendor": "U.S. Department of Veterans Affairs (National Center for PTSD) / DoD / Stanford",
    "platform": "Mobile",
    "url": "https://mobile.va.gov/app/cbt-i-coach",
    "country": "United States",
    "last_update": "Unknown",
    "stated_pop": "Adults engaged in CBT-I with a clinician; PTSD-related insomnia",
    "age_range": "18+",
    "ayaccs": "No",
    "adjacent_aya": "No",
    "general_adult": "Yes",
    "mobile": "Yes",
    "web": "No",
    "self_guided": "No",
    "therapist_guided": "Yes",
    "hybrid": "Yes",
    "ai_mediated": "No",
    "ucd": "Yes",
    "sdt": "Unknown",
    "psd": "Yes",
    "equity": "Unknown",
    "wcag": "Unknown",
    "cbt_comorbid": "No",
    "symptom_cluster": "No",
    "surv_fit": "No",
    "f_transdx": "No",
    "f_coping": "Yes",
    "f_transition": "No",
    "f_disclosure": "No",
    "f_pain_mind": "No",
    "f_gamif": "No",
    "f_clusters": "No",
    "f_cbt_cancer": "No",
    "f_jitai": "No",
    "f_peer": "No",
    "f_ccs_custom": "No",
    "f_late_glossary": "No",
    "s_anx": "Yes",
    "s_dep": "No",
    "s_pain": "No",
    "s_fatigue": "No",
    "s_sleep": "Yes",
    "s_cog": "No",
    "s_isolation": "No",
    "s_rumin": "Yes",
    "s_health_anx": "No",
    "s_other": "Yes",
    "note": "Single-symptom (insomnia). Evidence-based CBT-I scaffolding (sleep diary, tools, learn, assessments).",
    "elevator_pitch": "Free VA / DoD / Stanford-developed companion app for clinician-delivered CBT-I; sleep diary, in-the-moment tools, validated assessments, and psychoeducation for chronic insomnia (incl. PTSD-related).",
    "app_store_url": "https://apps.apple.com/us/app/cbt-i-coach/id655918660",
    "google_play_url": "https://play.google.com/store/apps/details?id=gov.va.mobilehealth.ncptsd.cbti",
    "usage_adoption": "Free; widely used across VA/DoD; clinician-perception study (Koffel et al., 2018) and pilot RCT support feasibility; v3 released 2023 with new features.",
    "cbt_location": "Sleep Diary; Tools (cognitive restructuring of sleep-related thoughts; relaxation; healthy sleep tips); Learn (CBT-I psychoeducation); Assessments.",
    "cbt_structure": "Companion to clinician-delivered CBT-I; not a stand-alone program.",
    "cbt_ui_examples": "Daily sleep-diary form, derived sleep-efficiency calculations, ISI weekly prompts, in-the-moment relaxation audio, sleep-thought-restructuring screens.",
    "all_features": "Daily sleep diary [CBT]; cognitive-restructuring tools [CBT]; relaxation exercises [CBT]; sleep-environment tips [CBT]; reminders; ISI / DBAS-16 assessments [CBT]; data export (xlsx) and Apple HealthKit / Google Fit integration; Learn library.",
    "cbt_concepts": "Sleep restriction, stimulus control, cognitive restructuring of sleep beliefs, relaxation, sleep hygiene, paradoxical intention.",
    "cbt_tools": "Sleep diary, relaxation audio, thought-restructuring forms.",
    "daily_content": "Daily sleep-diary completion; periodic ISI assessment.",
    "psychoeducation": "Substantial — Learn section is a CBT-I library.",
    "standardized_measures": "ISI (Insomnia Severity Index, weekly); DBAS-16 (Dysfunctional Beliefs and Attitudes about Sleep).",
    "other_assessments": "Derived sleep variables (efficiency, latency); HealthKit/Google Fit pull-ins.",
    "cbt_degree": "Core — pure CBT-I companion."
  },
  {
    "id": "TDI-023",
    "name": "Cool Kids Online",
    "vendor": "Macquarie University Emotional Health Clinic",
    "platform": "Web",
    "url": "https://coolkids.org.au/",
    "country": "Australia",
    "last_update": "Unknown",
    "stated_pop": "Parents of children 7-12 with anxiety (parent-led with child)",
    "age_range": "7-12 (with parent)",
    "ayaccs": "No",
    "adjacent_aya": "Yes",
    "general_adult": "No",
    "mobile": "No",
    "web": "Yes",
    "self_guided": "Yes",
    "therapist_guided": "Yes",
    "hybrid": "Yes",
    "ai_mediated": "No",
    "ucd": "Yes",
    "sdt": "Unknown",
    "psd": "Yes",
    "equity": "Unknown",
    "wcag": "Unknown",
    "cbt_comorbid": "No",
    "symptom_cluster": "No",
    "surv_fit": "No",
    "f_transdx": "No",
    "f_coping": "Yes",
    "f_transition": "No",
    "f_disclosure": "No",
    "f_pain_mind": "No",
    "f_gamif": "No",
    "f_clusters": "No",
    "f_cbt_cancer": "No",
    "f_jitai": "No",
    "f_peer": "No",
    "f_ccs_custom": "No",
    "f_late_glossary": "No",
    "s_anx": "Yes",
    "s_dep": "No",
    "s_pain": "No",
    "s_fatigue": "No",
    "s_sleep": "No",
    "s_cog": "No",
    "s_isolation": "No",
    "s_rumin": "Yes",
    "s_health_anx": "No",
    "s_other": "No",
    "note": "Single-symptom (anxiety). Parent-led 8-lesson CBT (text/cartoon/video).",
    "elevator_pitch": "Macquarie University Emotional Health Clinic's online CBT program for parents of anxious children 7-12 (parent-delivered with Macquarie therapist accreditation/oversight).",
    "app_store_url": "Unknown (web platform)",
    "google_play_url": "Unknown (web platform)",
    "usage_adoption": "20+ years of research support; deployed in Macquarie's Emotional Health Clinic and accredited-therapist programs; 60-75% of participants achieve anxiety-disorder-free status.",
    "cbt_location": "8 online lessons covering CBT skills for child-anxiety: psychoeducation, detective thinking (cognitive restructuring), facing fears (graded exposure), problem-solving, parent strategies.",
    "cbt_structure": "8 lessons over 10 weeks; parent-delivered with child; 4 brief calls with an accredited therapist for troubleshooting.",
    "cbt_ui_examples": "Lesson page with text + cartoons + parent-story videos; downloadable practice exercises; quizzes; parent-coach call schedule.",
    "all_features": "8 CBT lessons [CBT]; detective-thinking worksheet [CBT]; fear-ladder/stepladder [CBT]; behavioural experiments [CBT]; parent-strategy modules [CBT]; therapist support calls; downloadable practice exercises [CBT].",
    "cbt_concepts": "Cognitive restructuring (Detective Thinking), graded exposure (stepladder), behavioural experiments, problem solving, parent management strategies.",
    "cbt_tools": "Online lessons, worksheets, parent-coach calls.",
    "daily_content": "Weekly lesson + daily practice exercises.",
    "psychoeducation": "Strong — parent psychoeducation throughout.",
    "standardized_measures": "SCAS / SCAS-P; ADIS in clinic studies.",
    "other_assessments": "Parent / child anxiety ratings.",
    "cbt_degree": "Core — strict child-anxiety CBT."
  },
  {
    "id": "TDI-024",
    "name": "FearFighter",
    "vendor": "CCBT Ltd / Magellan Healthcare",
    "platform": "Web",
    "url": "https://fearfighter.cbtprogram.com/",
    "country": "United Kingdom",
    "last_update": "Unknown",
    "stated_pop": "Adults with panic disorder, phobias, social anxiety",
    "age_range": "18+",
    "ayaccs": "No",
    "adjacent_aya": "No",
    "general_adult": "Yes",
    "mobile": "No",
    "web": "Yes",
    "self_guided": "Yes",
    "therapist_guided": "Yes",
    "hybrid": "Yes",
    "ai_mediated": "No",
    "ucd": "Unknown",
    "sdt": "Unknown",
    "psd": "Yes",
    "equity": "Unknown",
    "wcag": "Unknown",
    "cbt_comorbid": "No",
    "symptom_cluster": "No",
    "surv_fit": "No",
    "f_transdx": "No",
    "f_coping": "Yes",
    "f_transition": "No",
    "f_disclosure": "No",
    "f_pain_mind": "No",
    "f_gamif": "No",
    "f_clusters": "No",
    "f_cbt_cancer": "No",
    "f_jitai": "No",
    "f_peer": "No",
    "f_ccs_custom": "No",
    "f_late_glossary": "No",
    "s_anx": "Yes",
    "s_dep": "No",
    "s_pain": "No",
    "s_fatigue": "No",
    "s_sleep": "No",
    "s_cog": "No",
    "s_isolation": "No",
    "s_rumin": "Unknown",
    "s_health_anx": "Unknown",
    "s_other": "No",
    "note": "Single-symptom (anxiety: phobia/panic). NICE-endorsed exposure-CBT.",
    "elevator_pitch": "NICE-endorsed, SAMHSA-recognised iCBT for anxiety, panic and phobias; 9-step exposure-based self-help program with optional clinician support, deployed in NHS and US health-plan settings.",
    "app_store_url": "https://apps.apple.com/us/app/fearfighter/id1230258838",
    "google_play_url": "Unknown",
    "usage_adoption": "20+ years of research and development; NICE-endorsed; SAMHSA-listed; Magellan Healthcare partner deployment in the US; 41% average GAD-7 reduction.",
    "cbt_location": "9 sequential CBT steps centred on exposure: Getting Started → How to Beat Fear → Anxiety Management → Challenging Thoughts → Core Beliefs → Exposure & SMART Goals → Exposure & Rehearsal → Continuing Exposure → Maintaining Gains.",
    "cbt_structure": "9 steps over ~10 weeks; each ~50 min; 1 step/week recommended; optional clinician contact between steps.",
    "cbt_ui_examples": "Web-based step pages with text, video vignettes, interactive worksheets; printable end-of-step worksheets; progress emails.",
    "all_features": "9 CBT steps [CBT]; thinking-error/cognitive-distortion identifier [CBT]; core-belief work [CBT]; SMART-goal setting [CBT]; exposure planner [CBT]; relapse-prevention plan [CBT]; printable worksheets [CBT]; email follow-ups; clinician portal.",
    "cbt_concepts": "Cognitive restructuring, anxiety management, graded exposure, behavioural experiments, core-belief work, SMART goals, relapse prevention.",
    "cbt_tools": "Online step pages, printable worksheets, exposure logs.",
    "daily_content": "Weekly step + between-step exposure homework.",
    "psychoeducation": "Strong — every step opens with focused psychoeducation.",
    "standardized_measures": "GAD-7 (primary); FearFighter outcomes scale; PHQ-9 in some deployments.",
    "other_assessments": "Exposure-task self-ratings.",
    "cbt_degree": "Core — strict exposure-based CBT."
  },
  {
    "id": "TDI-025",
    "name": "Clear Fear",
    "vendor": "stem4 (charity)",
    "platform": "Mobile",
    "url": "https://clearfear.stem4.org.uk/",
    "country": "United Kingdom",
    "last_update": "Unknown",
    "stated_pop": "Young people 11-19 with mild-to-moderate anxiety",
    "age_range": "11-19",
    "ayaccs": "No",
    "adjacent_aya": "Yes",
    "general_adult": "No",
    "mobile": "Yes",
    "web": "No",
    "self_guided": "Yes",
    "therapist_guided": "No",
    "hybrid": "No",
    "ai_mediated": "No",
    "ucd": "Yes",
    "sdt": "Unknown",
    "psd": "Yes",
    "equity": "Unknown",
    "wcag": "Unknown",
    "cbt_comorbid": "No",
    "symptom_cluster": "No",
    "surv_fit": "No",
    "f_transdx": "No",
    "f_coping": "Yes",
    "f_transition": "No",
    "f_disclosure": "No",
    "f_pain_mind": "No",
    "f_gamif": "No",
    "f_clusters": "No",
    "f_cbt_cancer": "No",
    "f_jitai": "No",
    "f_peer": "No",
    "f_ccs_custom": "No",
    "f_late_glossary": "No",
    "s_anx": "Yes",
    "s_dep": "No",
    "s_pain": "No",
    "s_fatigue": "No",
    "s_sleep": "No",
    "s_cog": "No",
    "s_isolation": "No",
    "s_rumin": "Yes",
    "s_health_anx": "No",
    "s_other": "No",
    "note": "Single-symptom (anxiety). CBT framework + breathing/relaxation/mindfulness exercises for adolescents.",
    "elevator_pitch": "Free stem4-developed CBT app for 11–19-year-olds with mild-to-moderate anxiety; CBT framework with breathing/relaxation/mindfulness exercises and a personalised 'safety net' of helpful contacts and behaviours.",
    "app_store_url": "https://apps.apple.com/us/app/clear-fear/id1437282350",
    "google_play_url": "https://play.google.com/store/apps/details?id=uk.org.stem4.clearfear",
    "usage_adoption": "Free; 40% increase in use post-pandemic per stem4; published evaluation (formative.jmir.org, 2025) reports 100% acceptability and statistically-significant anxiety reductions; companion app to stem4's Calm Harm (~900K downloads).",
    "cbt_location": "CBT framework underlies the whole app: change anxious thoughts (cognitive); alter anxious behaviours (behavioural); calm fear responses (physiological).",
    "cbt_structure": "Tool-first, not session-first; user opens 'Safety Net', 'Immediate Help', 'Grit Box', or 'Manage Anxiety' tools as needed.",
    "cbt_ui_examples": "Safety-net set-up flow (anxiety-reducing thoughts, coping behaviours, contacts); journaling screens; progress graphs; resource library; immediate-help SOS.",
    "all_features": "Safety Net set-up [CBT]; thought-record-style journaling [CBT]; cognitive-reappraisal exercises [CBT]; behavioural-activation activities [CBT]; breathing & relaxation [CBT]; mindfulness exercises; Immediate Help SOS; Grit Box (resilience); progress graphs; resources library.",
    "cbt_concepts": "Cognitive reappraisal, behavioural change, psychoeducation about anxiety types, relaxation, exposure (light).",
    "cbt_tools": "Journaling, safety-net builder, breathing/relaxation audio, progress graphs.",
    "daily_content": "User-driven; no enforced daily curriculum.",
    "psychoeducation": "Strong for an app of its size — explainers on different anxiety presentations and adaptive responses.",
    "standardized_measures": "Self-rated anxiety check-in; not PHQ/GAD by default.",
    "other_assessments": "Mood/anxiety progress graphs.",
    "cbt_degree": "Core — CBT is the explicit framework; mindfulness/breathing are auxiliary skills."
  },
  {
    "id": "TDI-026",
    "name": "MindDoc",
    "vendor": "MindDoc Health GmbH (Schön Klinik)",
    "platform": "Mobile",
    "url": "https://minddoc.com/us/en",
    "country": "Germany",
    "last_update": "Unknown",
    "stated_pop": "Adults (18+) with mild-to-moderate depression, anxiety, insomnia, eating disorders, or stress",
    "age_range": "18+",
    "ayaccs": "No",
    "adjacent_aya": "No",
    "general_adult": "Yes",
    "mobile": "Yes",
    "web": "No",
    "self_guided": "Yes",
    "therapist_guided": "No",
    "hybrid": "No",
    "ai_mediated": "No",
    "ucd": "Unknown",
    "sdt": "Unknown",
    "psd": "Unknown",
    "equity": "Unknown",
    "wcag": "Unknown",
    "cbt_comorbid": "Yes",
    "symptom_cluster": "Unknown",
    "surv_fit": "No",
    "f_transdx": "Yes",
    "f_coping": "Yes",
    "f_transition": "No",
    "f_disclosure": "No",
    "f_pain_mind": "No",
    "f_gamif": "No",
    "f_clusters": "No",
    "f_cbt_cancer": "No",
    "f_jitai": "No",
    "f_peer": "No",
    "f_ccs_custom": "No",
    "f_late_glossary": "No",
    "s_anx": "Yes",
    "s_dep": "Yes",
    "s_pain": "No",
    "s_fatigue": "No",
    "s_sleep": "Yes",
    "s_cog": "No",
    "s_isolation": "No",
    "s_rumin": "Unknown",
    "s_health_anx": "No",
    "s_other": "Yes",
    "note": "German consumer app (formerly Moodpath, rebranded 2020); EU MDR Class I medical device; DiGA listing withdrawn June 2025. Active RCTs in progress. Mixed CBT + mood tracking + mindfulness.",
    "elevator_pitch": "German CBT-informed mental-health app offering guided self-reflection, evidence-based courses, and daily mood check-ins for adults with mild-to-moderate depression, anxiety, insomnia, and stress.",
    "app_store_url": "https://apps.apple.com/us/app/minddoc-mental-health-support/id1052216403",
    "google_play_url": "https://play.google.com/store/apps/details?id=de.moodpath.android",
    "usage_adoption": "4.7★ from 29,000+ App Store ratings; formerly listed in Germany's BfArM DiGA directory (prescription-reimbursable); DiGA listing withdrawn June 2025; ISO 27001 certified; EU MDR Class I medical device; active RCTs via PMC8286775 and PMC10632923.",
    "cbt_location": "CBT appears in structured courses (depression, anxiety, insomnia, eating disorders) delivered as sequential modules with psychoeducation and interactive exercises; daily mood assessments feed into course recommendations.",
    "cbt_structure": "Structured course modules (8–12 sessions); daily 2-min check-ins; self-paced.",
    "cbt_ui_examples": "Daily mood + symptom check-in screens; course module pages with psychoeducation and interactive CBT exercises; progress charts showing symptom trends over time.",
    "all_features": "Daily symptom check-ins [CBT]; CBT-based transdiagnostic courses [CBT]; psychoeducation [CBT]; thought records [CBT]; behavioural activation [CBT]; mindfulness exercises; sleep hygiene modules; mood/symptom tracking; progress charts; journaling.",
    "cbt_concepts": "Cognitive restructuring, behavioural activation, psychoeducation, self-monitoring, relaxation, sleep hygiene.",
    "cbt_tools": "Structured course modules, mood/symptom check-in, journaling, progress charts.",
    "daily_content": "Daily 2-min check-in; one course module per day in structured programs.",
    "psychoeducation": "Strong — each course includes psychoeducation on the condition and on CBT techniques.",
    "standardized_measures": "PHQ-9 (depression) and GAD-7 (anxiety) administered in-app; used as primary outcomes in published RCTs.",
    "other_assessments": "Daily mood and symptom tracking (custom scales).",
    "cbt_degree": "Mixed — CBT-based courses are central but the app also includes mood tracking, journaling, and mindfulness without strict CBT framing."
  },
  {
    "id": "TDI-027",
    "name": "MindBeacon",
    "vendor": "MindBeacon Group Inc. (GreenShield Health)",
    "platform": "Web + Mobile",
    "url": "https://www.mindbeacon.com/",
    "country": "Canada",
    "last_update": "Unknown",
    "stated_pop": "Canadian adults with mild-to-moderate mental health concerns; employees via employer/insurance benefit plans",
    "age_range": "18+",
    "ayaccs": "No",
    "adjacent_aya": "No",
    "general_adult": "Yes",
    "mobile": "Yes",
    "web": "Yes",
    "self_guided": "No",
    "therapist_guided": "Yes",
    "hybrid": "Yes",
    "ai_mediated": "No",
    "ucd": "Unknown",
    "sdt": "Unknown",
    "psd": "Unknown",
    "equity": "Unknown",
    "wcag": "Unknown",
    "cbt_comorbid": "Yes",
    "symptom_cluster": "No",
    "surv_fit": "No",
    "f_transdx": "Yes",
    "f_coping": "Yes",
    "f_transition": "No",
    "f_disclosure": "No",
    "f_pain_mind": "Yes",
    "f_gamif": "No",
    "f_clusters": "No",
    "f_cbt_cancer": "No",
    "f_jitai": "No",
    "f_peer": "No",
    "f_ccs_custom": "No",
    "f_late_glossary": "No",
    "s_anx": "Yes",
    "s_dep": "Yes",
    "s_pain": "Yes",
    "s_fatigue": "No",
    "s_sleep": "Yes",
    "s_cog": "No",
    "s_isolation": "No",
    "s_rumin": "Unknown",
    "s_health_anx": "Yes",
    "s_other": "Yes",
    "note": "Canadian therapist-assisted iCBT platform; owned by GreenShield (non-profit insurer); primary channel is employer/insurance benefits. Operates as regulated healthcare service (not a cleared medical device). No independent peer-reviewed RCT of the platform; underlying CBT methodology is well-validated.",
    "elevator_pitch": "Canadian therapist-assisted iCBT platform offering structured CBT programs with asynchronous therapist messaging, live video therapy, and messaging counselling for anxiety, depression, PTSD, insomnia, chronic pain, and more.",
    "app_store_url": "Unknown",
    "google_play_url": "https://play.google.com/store/apps/details?id=io.mindbeacon",
    "usage_adoption": "Primarily accessed through employer benefit plans and GreenShield insurance; internal outcome analyses report 70%+ improvement rates in PTSD (n=122), anxiety, and depression programs; described as largest network of CBT clinics in Canada; HIPAA, PHIPA, PIPEDA compliant; AICPA SOC certified.",
    "cbt_location": "CBT is the primary therapeutic modality across all programs; structured iCBT modules delivered sequentially with asynchronous therapist feedback between sessions; content mirrors in-person CBT protocols.",
    "cbt_structure": "Sequential sessions (8–12 per program); asynchronous therapist review and feedback after each module; optional live video/phone therapy sessions.",
    "cbt_ui_examples": "Module-based program pages with psychoeducation, worksheets, and homework assignments; secure messaging interface with assigned therapist; session summaries and progress tracking.",
    "all_features": "Therapist-assigned iCBT programs [CBT]; asynchronous therapist messaging [CBT]; live video/phone therapy; psychoeducation modules [CBT]; CBT worksheets and homework [CBT]; mood/symptom tracking; progress monitoring; secure messaging counselling.",
    "cbt_concepts": "Cognitive restructuring, behavioural activation, exposure therapy (anxiety/PTSD), sleep restriction/hygiene (insomnia), problem-solving, psychoeducation, self-monitoring.",
    "cbt_tools": "Structured iCBT modules, CBT worksheets, asynchronous therapist messaging, live therapy sessions, progress tracking.",
    "daily_content": "Module-based (not strictly daily); therapist assigns pace; asynchronous communication between sessions.",
    "psychoeducation": "Strong — each program module begins with psychoeducation on the condition and CBT rationale.",
    "standardized_measures": "PHQ-9, GAD-7, PCL-5 (PTSD), ISI (insomnia) used as program outcome measures; reported in internal outcome analyses.",
    "other_assessments": "Therapist-administered intake assessments; ongoing symptom monitoring between modules.",
    "cbt_degree": "Core — explicitly therapist-assisted iCBT; all programs are structured CBT protocols with therapist oversight."
  }
];
